// This is a representative list and not exhaustive.
// Colors are based on the main fields of the flag.
export const COUNTRY_COLORS: Record<string, string[]> = {
  AFG: ['Black', 'Red', 'Green', 'White'],
  ALB: ['Red', 'Black'],
  DZA: ['Green', 'White', 'Red'],
  AND: ['Blue', 'Yellow', 'Red'],
  AGO: ['Red', 'Black', 'Yellow'],
  ARG: ['Blue', 'White', 'Yellow'],
  ARM: ['Red', 'Blue', 'Yellow'],
  AUS: ['Blue', 'Red', 'White'],
  AUT: ['Red', 'White'],
  AZE: ['Blue', 'Red', 'Green', 'White'],
  BHS: ['Blue', 'Yellow', 'Black'],
  BHR: ['Red', 'White'],
  BGD: ['Green', 'Red'],
  BRB: ['Blue', 'Yellow', 'Black'],
  BLR: ['Red', 'Green', 'White'],
  BEL: ['Black', 'Yellow', 'Red'],
  BLZ: ['Blue', 'Red', 'White'],
  BEN: ['Green', 'Yellow', 'Red'],
  BTN: ['Yellow', 'Red', 'White'],
  BOL: ['Red', 'Yellow', 'Green'],
  BIH: ['Blue', 'Yellow', 'White'],
  BWA: ['Blue', 'White', 'Black'],
  BRA: ['Green', 'Yellow', 'Blue', 'White'],
  BRN: ['Yellow', 'White', 'Black', 'Red'],
  BGR: ['White', 'Green', 'Red'],
  BFA: ['Red', 'Green', 'Yellow'],
  BDI: ['Red', 'Green', 'White'],
  KHM: ['Blue', 'Red', 'White'],
  CMR: ['Green', 'Red', 'Yellow'],
  CAN: ['Red', 'White'],
  CPV: ['Blue', 'White', 'Red', 'Yellow'],
  CAF: ['Blue', 'White', 'Green', 'Yellow', 'Red'],
  TCD: ['Blue', 'Yellow', 'Red'],
  CHL: ['White', 'Red', 'Blue'],
  CHN: ['Red', 'Yellow'],
  COL: ['Yellow', 'Blue', 'Red'],
  COM: ['Yellow', 'White', 'Red', 'Blue', 'Green'],
  COG: ['Green', 'Yellow', 'Red'],
  CRI: ['Blue', 'White', 'Red'],
  CIV: ['Red', 'White', 'Green'],
  HRV: ['Red', 'White', 'Blue'],
  CUB: ['Blue', 'White', 'Red'],
  CYP: ['White', 'Yellow', 'Green'],
  CZE: ['White', 'Red', 'Blue'],
  DNK: ['Red', 'White'],
  DJI: ['Blue', 'Green', 'White', 'Red'],
  DOM: ['Red', 'White', 'Blue'],
  ECU: ['Yellow', 'Blue', 'Red'],
  EGY: ['Red', 'White', 'Black', 'Yellow'],
  SLV: ['Blue', 'White'],
  GNQ: ['Green', 'White', 'Red', 'Blue'],
  ERI: ['Green', 'Red', 'Blue', 'Yellow'],
  EST: ['Blue', 'Black', 'White'],
  SWZ: ['Blue', 'Yellow', 'Red', 'Black', 'White'],
  ETH: ['Green', 'Yellow', 'Red', 'Blue'],
  FJI: ['Blue', 'White', 'Red'],
  FIN: ['White', 'Blue'],
  FRA: ['Blue', 'White', 'Red'],
  GAB: ['Green', 'Yellow', 'Blue'],
  GMB: ['Red', 'Blue', 'Green', 'White'],
  GEO: ['White', 'Red'],
  DEU: ['Black', 'Red', 'Yellow'],
  GHA: ['Red', 'Yellow', 'Green', 'Black'],
  GRC: ['Blue', 'White'],
  GTM: ['Blue', 'White'],
  GIN: ['Red', 'Yellow', 'Green'],
  GNB: ['Red', 'Yellow', 'Green', 'Black'],
  GUY: ['Green', 'White', 'Yellow', 'Black', 'Red'],
  HND: ['Blue', 'White'],
  HUN: ['Red', 'White', 'Green'],
  ISL: ['Blue', 'White', 'Red'],
  IND: ['Red', 'White', 'Green', 'Blue'],
  IDN: ['Red', 'White'],
  IRN: ['Green', 'White', 'Red'],
  IRQ: ['Red', 'White', 'Black', 'Green'],
  IRL: ['Green', 'White', 'Red'],
  ISR: ['White', 'Blue'],
  ITA: ['Green', 'White', 'Red'],
  JAM: ['Green', 'Yellow', 'Black'],
  JPN: ['White', 'Red'],
  JOR: ['Black', 'White', 'Green', 'Red'],
  KAZ: ['Blue', 'Yellow'],
  KEN: ['Black', 'Red', 'Green', 'White'],
  KWT: ['Green', 'White', 'Red', 'Black'],
  KGZ: ['Red', 'Yellow'],
  LAO: ['Red', 'Blue', 'White'],
  LVA: ['Red', 'White'],
  LBN: ['Red', 'White', 'Green'],
  LSO: ['Blue', 'White', 'Green', 'Black'],
  LBR: ['Red', 'White', 'Blue'],
  LBY: ['Red', 'Black', 'Green', 'White'],
  LIE: ['Blue', 'Red', 'Yellow'],
  LTU: ['Yellow', 'Green', 'Red'],
  LUX: ['Red', 'White', 'Blue'],
  MDG: ['White', 'Red', 'Green'],
  MWI: ['Black', 'Red', 'Green'],
  MYS: ['Red', 'White', 'Blue', 'Yellow'],
  MLI: ['Green', 'Yellow', 'Red'],
  MLT: ['White', 'Red'],
  MRT: ['Green', 'Yellow', 'Red'],
  MUS: ['Red', 'Blue', 'Yellow', 'Green'],
  MEX: ['Green', 'White', 'Red'],
  MDA: ['Blue', 'Yellow', 'Red'],
  MCO: ['Red', 'White'],
  MNG: ['Red', 'Blue', 'Yellow'],
  MNE: ['Red', 'Yellow'],
  MAR: ['Red', 'Green'],
  MOZ: ['Green', 'Black', 'Yellow', 'White', 'Red'],
  MMR: ['Yellow', 'Green', 'Red', 'White'],
  NAM: ['Blue', 'Red', 'Green', 'White', 'Yellow'],
  NPL: ['Red', 'Blue', 'White'],
  NLD: ['Red', 'White', 'Blue'],
  NZL: ['Blue', 'Red', 'White'],
  NIC: ['Blue', 'White'],
  NER: ['Red', 'White', 'Green'],
  NGA: ['Green', 'White'],
  MKD: ['Red', 'Yellow'],
  NOR: ['Red', 'White', 'Blue'],
  OMN: ['White', 'Red', 'Green'],
  PAK: ['Green', 'White'],
  PAN: ['White', 'Red', 'Blue'],
  PNG: ['Red', 'Black', 'Yellow', 'White'],
  PRY: ['Red', 'White', 'Blue'],
  PER: ['Red', 'White'],
  PHL: ['Blue', 'Red', 'White', 'Yellow'],
  POL: ['White', 'Red'],
  PRT: ['Green', 'Red', 'Yellow', 'White', 'Blue'],
  QAT: ['White', 'Red'],
  ROU: ['Blue', 'Yellow', 'Red'],
  RUS: ['White', 'Blue', 'Red'],
  RWA: ['Blue', 'Yellow', 'Green'],
  KNA: ['Green', 'Yellow', 'Red', 'Black', 'White'],
  LCA: ['Blue', 'Yellow', 'White', 'Black'],
  VCT: ['Blue', 'Yellow', 'Green'],
  WSM: ['Red', 'Blue', 'White'],
  SMR: ['White', 'Blue'],
  STP: ['Green', 'Yellow', 'Red', 'Black'],
  SAU: ['Green', 'White'],
  SEN: ['Green', 'Yellow', 'Red'],
  SRB: ['Red', 'Blue', 'White'],
  SLE: ['Green', 'White', 'Blue'],
  SGP: ['Red', 'White'],
  SVK: ['White', 'Blue', 'Red'],
  SVN: ['White', 'Blue', 'Red'],
  SOM: ['Blue', 'White'],
  ZAF: ['Red', 'White', 'Green', 'Yellow', 'Black', 'Blue'],
  KOR: ['White', 'Black', 'Red', 'Blue'],
  SSD: ['Black', 'White', 'Red', 'Green', 'Blue', 'Yellow'],
  ESP: ['Red', 'Yellow'],
  LKA: ['Yellow', 'Red', 'Green', 'Black'],
  SDN: ['Red', 'White', 'Black', 'Green'],
  SUR: ['Green', 'White', 'Red', 'Yellow'],
  SWE: ['Blue', 'Yellow'],
  CHE: ['Red', 'White'],
  SYR: ['Red', 'White', 'Black', 'Green'],
  TZA: ['Green', 'Yellow', 'Black', 'Blue'],
  THA: ['Red', 'White', 'Blue'],
  TLS: ['Red', 'Yellow', 'Black', 'White'],
  TGO: ['Green', 'Yellow', 'Red', 'White'],
  TTO: ['Red', 'White', 'Black'],
  TUN: ['Red', 'White'],
  TUR: ['Red', 'White'],
  UGA: ['Black', 'Yellow', 'Red', 'White'],
  UKR: ['Blue', 'Yellow'],
  ARE: ['Green', 'White', 'Black', 'Red'],
  GBR: ['Red', 'White', 'Blue'],
  USA: ['Red', 'White', 'Blue'],
  URY: ['White', 'Blue', 'Yellow'],
  UZB: ['Blue', 'White', 'Green', 'Red'],
  VUT: ['Red', 'Green', 'Black', 'Yellow'],
  VEN: ['Yellow', 'Blue', 'Red', 'White'],
  VNM: ['Red', 'Yellow'],
  YEM: ['Red', 'White', 'Black'],
  ZMB: ['Green', 'Red', 'Black', 'Red'],
  ZWE: ['Green', 'Yellow', 'Red', 'Black', 'White'],
};
