
export const COUNTRY_NAMES_PT: Record<string, string> = {
    // Américas
    'USA': 'Estados Unidos',
    'CAN': 'Canadá',
    'MEX': 'México',
    'BRA': 'Brasil',
    'ARG': 'Argentina',
    'CHL': 'Chile',
    'COL': 'Colômbia',
    'PER': 'Peru',
    'VEN': 'Venezuela',
    'URY': 'Uruguai',
    'PRY': 'Paraguai',
    'BOL': 'Bolívia',
    'ECU': 'Equador',
    'DOM': 'República Dominicana',
    'CUB': 'Cuba',
    'JAM': 'Jamaica',
    'HTI': 'Haiti',
    'PAN': 'Panamá',
    'CRI': 'Costa Rica',
    'GTM': 'Guatemala',
    'HND': 'Honduras',
    'NIC': 'Nicarágua',
    'SLV': 'El Salvador',
    'TTO': 'Trinidad e Tobago',
    'GUY': 'Guiana',
    'SUR': 'Suriname',

    // Europa
    'PRT': 'Portugal',
    'ESP': 'Espanha',
    'FRA': 'França',
    'ITA': 'Itália',
    'DEU': 'Alemanha',
    'GBR': 'Reino Unido',
    'IRL': 'Irlanda',
    'BEL': 'Bélgica',
    'NLD': 'Países Baixos',
    'LUX': 'Luxemburgo',
    'CHE': 'Suíça',
    'AUT': 'Áustria',
    'GRC': 'Grécia',
    'DNK': 'Dinamarca',
    'SWE': 'Suécia',
    'NOR': 'Noruega',
    'FIN': 'Finlândia',
    'ISL': 'Islândia',
    'POL': 'Polônia',
    'CZE': 'Tchéquia',
    'SVK': 'Eslováquia',
    'HUN': 'Hungria',
    'ROU': 'Romênia',
    'BGR': 'Bulgária',
    'UKR': 'Ucrânia',
    'RUS': 'Rússia',
    'BLR': 'Belarus',
    'SRB': 'Sérvia',
    'HRV': 'Croácia',
    'SVN': 'Eslovênia',
    'BIH': 'Bósnia e Herzegovina',
    'MNE': 'Montenegro',
    'MKD': 'Macedônia do Norte',
    'ALB': 'Albânia',
    'EST': 'Estônia',
    'LVA': 'Letônia',
    'LTU': 'Lituânia',
    'MLT': 'Malta',
    'CYP': 'Chipre',
    'AND': 'Andorra',
    'MCO': 'Mônaco',
    'SMR': 'San Marino',
    'VAT': 'Vaticano',
    'LIE': 'Liechtenstein',

    // Ásia
    'JPN': 'Japão',
    'CHN': 'China',
    'KOR': 'Coreia do Sul',
    'PRK': 'Coreia do Norte',
    'IND': 'Índia',
    'IDN': 'Indonésia',
    'THA': 'Tailândia',
    'VNM': 'Vietnã',
    'PHL': 'Filipinas',
    'MYS': 'Malásia',
    'SGP': 'Singapura',
    'TUR': 'Turquia',
    'ISR': 'Israel',
    'SAU': 'Arábia Saudita',
    'ARE': 'Emirados Árabes',
    'QAT': 'Catar',
    'KWT': 'Kuwait',
    'BHR': 'Bahrein',
    'OMN': 'Omã',
    'YEM': 'Iêmen',
    'IRQ': 'Iraque',
    'IRN': 'Irã',
    'SYR': 'Síria',
    'LBN': 'Líbano',
    'JOR': 'Jordânia',
    'PSE': 'Palestina',
    'KAZ': 'Cazaquistão',
    'UZB': 'Uzbequistão',
    'TKM': 'Turcomenistão',
    'KGZ': 'Quirguistão',
    'TJK': 'Tajiquistão',
    'AFG': 'Afeganistão',
    'PAK': 'Paquistão',
    'BGD': 'Bangladesh',
    'LKA': 'Sri Lanka',
    'MMR': 'Mianmar',
    'KHM': 'Camboja',
    'LAO': 'Laos',
    'MNG': 'Mongólia',
    'TWN': 'Taiwan',

    // África
    'EGY': 'Egito',
    'ZAF': 'África do Sul',
    'NGA': 'Nigéria',
    'KEN': 'Quênia',
    'MAR': 'Marrocos',
    'DZA': 'Argélia',
    'TUN': 'Tunísia',
    'LBY': 'Líbia',
    'ETH': 'Etiópia',
    'SDN': 'Sudão',
    'SSD': 'Sudão do Sul',
    'UGA': 'Uganda',
    'GHA': 'Gana',
    'CIV': 'Costa do Marfim',
    'CMR': 'Camarões',
    'SEN': 'Senegal',
    'AGO': 'Angola',
    'MOZ': 'Moçambique',
    'CPV': 'Cabo Verde',
    'GNB': 'Guiné-Bissau',
    'STP': 'São Tomé e Príncipe',
    'TLS': 'Timor-Leste',
    'GNQ': 'Guiné Equatorial',
    'COD': 'RD Congo',
    'COG': 'Congo',
    'MDG': 'Madagascar',
    'ZWE': 'Zimbábue',
    'ZMB': 'Zâmbia',
    'NAM': 'Namíbia',
    'BWA': 'Botsuana',

    // Oceania
    'AUS': 'Austrália',
    'NZL': 'Nova Zelândia',
    'FJI': 'Fiji',
    'PNG': 'Papua-Nova Guiné',
    'WSM': 'Samoa',
    'VUT': 'Vanuatu',
    'SLB': 'Ilhas Salomão',
    'KIR': 'Kiribati',
    'TON': 'Tonga',
};
