
export const COUNTRY_NAMES_PT: Record<string, string> = {
    // Américas
    'USA': 'Estados Unidos',
    'CAN': 'Canadá',
    'MEX': 'México',
    'BRA': 'Brasil',
    'ARG': 'Argentina',
    'CHL': 'Chile',
    'COL': 'Colômbia',
    'PER': 'Peru',
    'VEN': 'Venezuela',
    'URY': 'Uruguai',
    'PRY': 'Paraguai',
    'BOL': 'Bolívia',
    'ECU': 'Equador',
    'DOM': 'República Dominicana',
    'CUB': 'Cuba',
    'JAM': 'Jamaica',
    'HTI': 'Haiti',
    'PAN': 'Panamá',
    'CRI': 'Costa Rica',
    'GTM': 'Guatemala',
    'HND': 'Honduras',
    'NIC': 'Nicarágua',
    'SLV': 'El Salvador',
    'TTO': 'Trinidad e Tobago',
    'GUY': 'Guiana',
    'SUR': 'Suriname',
    'ABW': 'Aruba',
    'AIA': 'Anguila',
    'ATG': 'Antígua e Barbuda',
    'BHS': 'Bahamas',
    'BRB': 'Barbados',
    'BES': 'Países Baixos Caribenhos',
    'BMU': 'Bermudas',
    'VGB': 'Ilhas Virgens Britânicas',
    'CYM': 'Ilhas Cayman',
    'CUW': 'Curaçao',
    'DMA': 'Dominica',
    'GRD': 'Granada',
    'GLP': 'Guadalupe',
    'MTQ': 'Martinica',
    'MSR': 'Montserrat',
    'PRI': 'Porto Rico',
    'BLM': 'São Bartolomeu',
    'KNA': 'São Cristóvão e Névis',
    'LCA': 'Santa Lúcia',
    'MAF': 'São Martinho',
    'SXM': 'Sint Maarten',
    'VCT': 'São Vicente e Granadinas',
    'TCA': 'Ilhas Turks e Caicos',
    'VIR': 'Ilhas Virgens Americanas',
    'FLK': 'Ilhas Malvinas',
    'GUF': 'Guiana Francesa',
    'GRL': 'Groenlândia',
    'SPM': 'São Pedro e Miquelão',

    // Europa
    'PRT': 'Portugal',
    'ESP': 'Espanha',
    'FRA': 'França',
    'ITA': 'Itália',
    'DEU': 'Alemanha',
    'GBR': 'Reino Unido',
    'IRL': 'Irlanda',
    'BEL': 'Bélgica',
    'NLD': 'Países Baixos',
    'LUX': 'Luxemburgo',
    'CHE': 'Suíça',
    'AUT': 'Áustria',
    'GRC': 'Grécia',
    'DNK': 'Dinamarca',
    'SWE': 'Suécia',
    'NOR': 'Noruega',
    'FIN': 'Finlândia',
    'ISL': 'Islândia',
    'POL': 'Polônia',
    'CZE': 'Tchéquia',
    'SVK': 'Eslováquia',
    'HUN': 'Hungria',
    'ROU': 'Romênia',
    'BGR': 'Bulgária',
    'UKR': 'Ucrânia',
    'RUS': 'Rússia',
    'BLR': 'Belarus',
    'SRB': 'Sérvia',
    'HRV': 'Croácia',
    'SVN': 'Eslovênia',
    'BIH': 'Bósnia e Herzegovina',
    'MNE': 'Montenegro',
    'MKD': 'Macedônia do Norte',
    'ALB': 'Albânia',
    'EST': 'Estônia',
    'LVA': 'Letônia',
    'LTU': 'Lituânia',
    'MLT': 'Malta',
    'CYP': 'Chipre',
    'AND': 'Andorra',
    'MCO': 'Mônaco',
    'SMR': 'San Marino',
    'VAT': 'Vaticano',
    'LIE': 'Liechtenstein',
    'FRO': 'Ilhas Faroé',
    'GIB': 'Gibraltar',
    'GGY': 'Guernsey',
    'IMN': 'Ilha de Man',
    'JEY': 'Jersey',
    'SJM': 'Svalbard e Jan Mayen',
    'ALA': 'Ilhas Aland',

    // Ásia
    'JPN': 'Japão',
    'CHN': 'China',
    'KOR': 'Coreia do Sul',
    'PRK': 'Coreia do Norte',
    'IND': 'Índia',
    'IDN': 'Indonésia',
    'THA': 'Tailândia',
    'VNM': 'Vietnã',
    'PHL': 'Filipinas',
    'MYS': 'Malásia',
    'SGP': 'Singapura',
    'TUR': 'Turquia',
    'ISR': 'Israel',
    'SAU': 'Arábia Saudita',
    'ARE': 'Emirados Árabes',
    'QAT': 'Catar',
    'KWT': 'Kuwait',
    'BHR': 'Bahrein',
    'OMN': 'Omã',
    'YEM': 'Iêmen',
    'IRQ': 'Iraque',
    'IRN': 'Irã',
    'SYR': 'Síria',
    'LBN': 'Líbano',
    'JOR': 'Jordânia',
    'PSE': 'Palestina',
    'KAZ': 'Cazaquistão',
    'UZB': 'Uzbequistão',
    'TKM': 'Turcomenistão',
    'KGZ': 'Quirguistão',
    'TJK': 'Tajiquistão',
    'AFG': 'Afeganistão',
    'PAK': 'Paquistão',
    'BGD': 'Bangladesh',
    'LKA': 'Sri Lanka',
    'MMR': 'Mianmar',
    'KHM': 'Camboja',
    'LAO': 'Laos',
    'MNG': 'Mongólia',
    'TWN': 'Taiwan',
    'ARM': 'Armênia',
    'AZE': 'Azerbaijão',
    'GEO': 'Geórgia',
    'BRN': 'Brunei',
    'TLS': 'Timor-Leste',
    'MDV': 'Maldivas',
    'BTN': 'Butão',
    'NPL': 'Nepal',
    'HKG': 'Hong Kong',
    'MAC': 'Macau',

    // África
    'EGY': 'Egito',
    'ZAF': 'África do Sul',
    'NGA': 'Nigéria',
    'KEN': 'Quênia',
    'MAR': 'Marrocos',
    'DZA': 'Argélia',
    'TUN': 'Tunísia',
    'LBY': 'Líbia',
    'ETH': 'Etiópia',
    'SDN': 'Sudão',
    'SSD': 'Sudão do Sul',
    'UGA': 'Uganda',
    'GHA': 'Gana',
    'CIV': 'Costa do Marfim',
    'CMR': 'Camarões',
    'SEN': 'Senegal',
    'AGO': 'Angola',
    'MOZ': 'Moçambique',
    'CPV': 'Cabo Verde',
    'GNB': 'Guiné-Bissau',
    'STP': 'São Tomé e Príncipe',
    'GNQ': 'Guiné Equatorial',
    'COD': 'RD Congo',
    'COG': 'Congo',
    'MDG': 'Madagascar',
    'ZWE': 'Zimbábue',
    'ZMB': 'Zâmbia',
    'NAM': 'Namíbia',
    'BWA': 'Botsuana',
    'BEN': 'Benim',
    'BFA': 'Burquina Faso',
    'BDI': 'Burundi',
    'CAF': 'República Centro-Africana',
    'TCD': 'Chade',
    'COM': 'Comores',
    'DJI': 'Djibuti',
    'ERI': 'Eritreia',
    'GAB': 'Gabão',
    'GMB': 'Gâmbia',
    'GIN': 'Guiné',
    'LSO': 'Lesoto',
    'LBR': 'Libéria',
    'MWI': 'Malaui',
    'MLI': 'Mali',
    'MRT': 'Mauritânia',
    'MUS': 'Maurício',
    'MYT': 'Mayotte',
    'NER': 'Níger',
    'REU': 'Reunião',
    'RWA': 'Ruanda',
    'SHN': 'Santa Helena',
    'SYC': 'Seicheles',
    'SLE': 'Serra Leoa',
    'SOM': 'Somália',
    'SWZ': 'Essuatíni',
    'TZA': 'Tanzânia',
    'TGO': 'Togo',
    'ESH': 'Saara Ocidental',

    // Oceania
    'AUS': 'Austrália',
    'NZL': 'Nova Zelândia',
    'FJI': 'Fiji',
    'PNG': 'Papua-Nova Guiné',
    'WSM': 'Samoa',
    'VUT': 'Vanuatu',
    'SLB': 'Ilhas Salomão',
    'KIR': 'Kiribati',
    'TON': 'Tonga',
    'ASM': 'Samoa Americana',
    'COK': 'Ilhas Cook',
    'PYF': 'Polinésia Francesa',
    'GUM': 'Guam',
    'MHL': 'Ilhas Marshall',
    'FSM': 'Micronésia',
    'NRU': 'Nauru',
    'NCL': 'Nova Caledônia',
    'NIU': 'Niue',
    'NFK': 'Ilha Norfolk',
    'MNP': 'Ilhas Marianas do Norte',
    'PLW': 'Palau',
    'PCN': 'Ilhas Pitcairn',
    'TKL': 'Toquelau',
    'TUV': 'Tuvalu',
    'WLF': 'Wallis e Futuna',

    // Antártida e Outros
    'ATA': 'Antártida',
    'BVT': 'Ilha Bouvet',
    'HMD': 'Ilhas Heard e McDonald',
    'IOT': 'Território Britânico do Oceano Índico',
    'ATF': 'Territórios Franceses do Sul',
    'SGS': 'Ilhas Geórgia do Sul e Sandwich do Sul',
    'UMI': 'Ilhas Menores Distantes dos EUA',
};
