import React, { createContext, useState, useContext, ReactNode, useEffect, useCallback } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string, replacements?: { [key: string]: string }) => string;
}

const translations: { [lang in Language]: { [key: string]: string } } = {
  en: {
    title: "Flags of the World Explorer",
    headerTitle: "Flags of the World",
    explorer: "Explorer",
    exploreTitle: "Flag of the Day",
    exploreSubtitle: "Discover the stories, symbols, and colors behind the flags of nations. Use the filters below to navigate through the rich tapestry of global heraldry.",
    searchPlaceholder: "Search by country name...",
    fetchError: "Failed to fetch country data. Please try again later.",
    errorOops: "Oops! Something went wrong.",
    noResults: "No flags match your search criteria.",
    noFlagsFound: "No Flags Found",
    noFlagsFoundDescription: "Try adjusting your search or filter to find what you're looking for.",
    viewDetailsFor: "View details for {{countryName}}",
    closeModal: "Close modal",
    continents: "Continent(s)",
    capital: "Capital",
    population: "Population",
    area: "Area",
    areaUnit: "km²",
    coatOfArms: "Coat of Arms",
    viewOnMap: "View on Google Maps",
    goToTop: "Go to top",
    footerRights: `© ${new Date().getFullYear()} Flags of the World Explorer. All rights reserved.`,
    footerBuiltWith: "Built with React & Tailwind CSS | Data from REST Countries API",
    showingFlags: "Showing {{count}} of {{total}} flags",
    loadingFlags: "Loading flags from around the globe...",
    startQuiz: "Start Quiz",
    quizTitle: "Quiz",
    questionOf: "Question {{current}} of {{total}}",
    whichCountry: "Which country's flag is this?",
    whichFlag: "Which flag belongs to {{country}}?",
    nextQuestion: "Next Question",
    quizResults: "Quiz Results",
    yourScore: "You scored {{score}} out of {{total}}",
    playAgain: "Play Again",
    backToExplorer: "Back to Explorer",
    scoreFeedbackExcellent: "Excellent! You're a flag expert!",
    scoreFeedbackGood: "Good job! You know your flags well.",
    scoreFeedbackAverage: "Not bad! A little more practice and you'll be an expert.",
    scoreFeedbackPoor: "Keep practicing! The world of flags is fascinating.",
    discoverTitle: "Discover",
    discoverLoading: "Curating a new collection for you...",
    flagOfTheDay: "Flag of the Day",
    flagOfTheDayLoading: "Selecting today's featured flag...",
    filterAndSearch: "Filter & Search",
    filterByContinent: "Filter by Continent",
    quizSetupTitle: "Quiz Setup",
    chooseMode: "Choose a Game Mode",
    selectDifficulty: "Select Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    difficultyEasyDesc: "Most populous countries.",
    difficultyMediumDesc: "A mix of all countries.",
    difficultyHardDesc: "Lesser-known countries.",
    modeFlagToCountry: "Flag ➞ Country",
    modeFlagToCountryDesc: "Guess the country from its flag.",
    modeCountryToFlag: "Country ➞ Flag",
    modeCountryToFlagDesc: "Find the correct flag for the country.",
    modeFlagToCapital: "Flag ➞ Capital",
    modeFlagToCapitalDesc: "Identify the capital from the flag.",
    modeCountryToCapital: "Country ➞ Capital",
    modeCountryToCapitalDesc: "Guess the capital of the country.",
    whichCapitalForCountry: "What is the capital of {{country}}?",
    modeShapeToCountry: "Coat of Arms ➞ Country",
    modeShapeToCountryDesc: "Recognize the country by its coat of arms.",
    whichCapital: "Which capital city does this flag belong to?",
    whichCoatOfArms: "Which country's coat of arms is this?",
    backToMenu: "Back to Menu",
    quizTime: "Total Time",
    quizAvgTime: "Avg. Time / Q",
    quizSeconds: "{{seconds}}s",
    compareMode: "Compare Mode",
    compareModeTooltip: "Toggle to select two flags for comparison",
    exitCompareMode: "Exit Compare Mode",
    selectForComparison: "Select {{countryName}} for comparison",
    compareFlags: "Compare ({{count}}/2)",
    clearSelection: "Clear",
    comparisonTitle: "Flag Comparison",
    favorites: "Favorites",
    noFavorites: "No favorites yet!",
    noFavoritesDescription: "Click the heart on any flag to add it to your collection.",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    addedToFavoritesToast: "{{countryName}} added to favorites!",
    removedFromFavoritesToast: "{{countryName}} removed from favorites.",
    toggleTheme: "Toggle theme",
    continentTab: "Continents",
    toolsTab: "Tools",
    quizStreak: "🔥 {{count}} Streak",
    quizHint: "Hint ({{count}} left)",
    quizNoHints: "No hints left",
    quizReviewAnswers: "Review Answers",
    quizBackToSummary: "Back to Summary",
    quizReviewTitle: "Quiz Review",
    quizYourAnswer: "Your answer:",
    quizCorrectAnswer: "Correct answer:",
    continentHint: "Hint: The country is in {{continent}}.",
    quizBestStreak: "Best Streak",
    quizAccuracy: "Accuracy",
    quizRank: "Your Rank",
    rankNovice: "Flag Novice",
    rankApprentice: "Flag Apprentice",
    rankAdept: "Vexillology Adept",
    rankExpert: "Flag Expert",
    rankMaster: "Geography Genius",
    quiz5050Hint: "50:50 ({{count}} left)",
    quizNo5050Hints: "No 50:50s left",
    quizCorrect: "Correct",
    quizIncorrect: "Incorrect",
    sortBy: "Sort by",
    sortNameAsc: "Name (A-Z)",
    sortNameDesc: "Name (Z-A)",
    sortPopAsc: "Population (Low-High)",
    sortPopDesc: "Population (High-Low)",
    sortAreaAsc: "Area (Low-High)",
    sortAreaDesc: "Area (High-Low)",
    selectACountry: "Select a Country",
    discoverIntro: "Dive deeper into the world of vexillology. Explore common themes, unique designs, and the rich symbolism embedded in the world's flags.",
    uniqueFlags: "Unique Flags",
    uniqueFlagOfTheDayTitle: "Unique Flag of the Day",
    nepalFlag: "Nepal",
    nepalFlagDesc: "The only non-quadrilateral national flag in the world.",
    switzerlandFlag: "Switzerland",
    switzerlandFlagDesc: "One of only two square-shaped sovereign-state flags (the other being Vatican City).",
    vaticanFlag: "Vatican City",
    vaticanFlagDesc: "One of only two square-shaped sovereign-state flags (the other being Switzerland).",
    symbolism: "Common Symbols",
    sunSymbol: "Sun",
    sunSymbolDesc: "Represents unity, life, and energy. Prominently featured on the flags of Japan and Argentina.",
    moonSymbol: "Moon / Crescent",
    moonSymbolDesc: "Often represents divinity and is a key symbol in many Muslim-majority nations like Turkey.",
    crossSymbol: "Cross",
    crossSymbolDesc: "A symbol of Christianity, central to the design of many European flags, especially in Scandinavia.",
    starsSymbol: "Stars",
    starsSymbolDesc: "Can represent states (USA), constellations (Brazil), or aspirations (China).",
    filterByColor: "Filter by Color",
    colorsTab: "Colors",
    flagFactsTitle: "Vexillology Vignettes",
    showAnotherFact: "Show another fact",
    flagFactsList: JSON.stringify([
      "The study of flags is called **vexillology**. The term was coined in 1957 by American scholar Whitney Smith.",
      "The flag of the Philippines is flown with the red stripe up in times of war and the blue stripe up in times of peace.",
      "The flag of Paraguay is unique because it has different emblems on its front (obverse) and back (reverse) sides.",
      "The only national flag that consisted of a single color was the flag of Libya from 1977 to 2011, which was solid green.",
      "The Union Jack of the United Kingdom is a combination of three flags: St. George's Cross (England), St. Andrew's Saltire (Scotland), and St. Patrick's Saltire (Ireland).",
      "The flag of Denmark, the Dannebrog, is the oldest continuously used national flag in the world, dating back to 1219.",
      "A white flag is an internationally recognized symbol of truce, ceasefire, and surrender.",
      "The flag of Mozambique is the only national flag to feature a modern assault rifle, an AK-47."
    ])
  },
  pt: {
    title: "Explorador de Bandeiras do Mundo",
    headerTitle: "Bandeiras do Mundo",
    explorer: "Explorador",
    exploreTitle: "Bandeira do Dia",
    exploreSubtitle: "Descubra as histórias, símbolos e cores por trás das bandeiras das nações. Use os filtros abaixo para navegar pela rica tapeçaria da heráldica global.",
    searchPlaceholder: "Pesquisar por nome do país...",
    fetchError: "Falha ao buscar dados dos países. Por favor, tente novamente mais tarde.",
    errorOops: "Opa! Algo deu errado.",
    noResults: "Nenhuma bandeira corresponde aos seus critérios de pesquisa.",
    noFlagsFound: "Nenhuma Bandeira Encontrada",
    noFlagsFoundDescription: "Tente ajustar sua busca ou filtro para encontrar o que procura.",
    viewDetailsFor: "Ver detalhes de {{countryName}}",
    closeModal: "Fechar modal",
    continents: "Continente(s)",
    capital: "Capital",
    population: "População",
    area: "Área",
    areaUnit: "km²",
    coatOfArms: "Brasão de Armas",
    viewOnMap: "Ver no Google Maps",
    goToTop: "Ir para o topo",
    footerRights: `© ${new Date().getFullYear()} Explorador de Bandeiras do Mundo. Todos os direitos reservados.`,
    footerBuiltWith: "Construído com React & Tailwind CSS | Dados da API REST Countries",
    showingFlags: "Mostrando {{count}} de {{total}} bandeiras",
    loadingFlags: "Carregando bandeiras de todo o mundo...",
    startQuiz: "Iniciar Quiz",
    quizTitle: "Quiz",
    questionOf: "Questão {{current}} de {{total}}",
    whichCountry: "De que país é esta bandeira?",
    whichFlag: "Qual bandeira pertence a {{country}}?",
    nextQuestion: "Próxima Pergunta",
    quizResults: "Resultados do Quiz",
    yourScore: "Você acertou {{score}} de {{total}}",
    playAgain: "Jogar Novamente",
    backToExplorer: "Voltar ao Explorador",
    scoreFeedbackExcellent: "Excelente! Você é um expert em bandeiras!",
    scoreFeedbackGood: "Bom trabalho! Você conhece bem as bandeiras.",
    scoreFeedbackAverage: "Nada mal! Com um pouco mais de prática você será um expert.",
    scoreFeedbackPoor: "Continue praticando! O mundo das bandeiras é fascinante.",
    discoverTitle: "Descubra",
    discoverLoading: "Criando uma nova coleção para você...",
    flagOfTheDay: "Bandeira do Dia",
    flagOfTheDayLoading: "Selecionando a bandeira em destaque de hoje...",
    filterAndSearch: "Filtrar e Pesquisar",
    filterByContinent: "Filtrar por Continente",
    quizSetupTitle: "Configuração do Quiz",
    chooseMode: "Escolha um Modo de Jogo",
    selectDifficulty: "Selecione a Dificuldade",
    difficultyEasy: "Fácil",
    difficultyMedium: "Médio",
    difficultyHard: "Difícil",
    difficultyEasyDesc: "Países mais populosos.",
    difficultyMediumDesc: "Uma mistura de todos os países.",
    difficultyHardDesc: "Países menos conhecidos.",
    modeFlagToCountry: "Bandeira ➞ País",
    modeFlagToCountryDesc: "Adivinhe o país pela bandeira.",
    modeCountryToFlag: "País ➞ Bandeira",
    modeCountryToFlagDesc: "Encontre a bandeira correta para o país.",
    modeFlagToCapital: "Bandeira ➞ Capital",
    modeFlagToCapitalDesc: "Identifique a capital pela bandeira.",
    modeCountryToCapital: "País ➞ Capital",
    modeCountryToCapitalDesc: "Adivinhe a capital do país.",
    whichCapitalForCountry: "Qual é a capital de {{country}}?",
    modeShapeToCountry: "Brasão ➞ País",
    modeShapeToCountryDesc: "Reconheça o país pelo seu brasão de armas.",
    whichCapital: "A qual cidade capital esta bandeira pertence?",
    whichCoatOfArms: "De que país é este brasão de armas?",
    backToMenu: "Voltar ao Menu",
    quizTime: "Tempo Total",
    quizAvgTime: "Tempo Médio / Q",
    quizSeconds: "{{seconds}}s",
    compareMode: "Modo de Comparação",
    compareModeTooltip: "Ative para selecionar duas bandeiras para comparação",
    exitCompareMode: "Sair do Modo de Comparação",
    selectForComparison: "Selecionar {{countryName}} para comparação",
    compareFlags: "Comparar ({{count}}/2)",
    clearSelection: "Limpar",
    comparisonTitle: "Comparação de Bandeiras",
    favorites: "Favoritos",
    noFavorites: "Nenhum favorito ainda!",
    noFavoritesDescription: "Clique no coração em qualquer bandeira para adicioná-la à sua coleção.",
    addToFavorites: "Adicionar aos favoritos",
    removeFromFavorites: "Remover dos favoritos",
    addedToFavoritesToast: "{{countryName}} adicionado aos favoritos!",
    removedFromFavoritesToast: "{{countryName}} removido dos favoritos.",
    toggleTheme: "Alternar tema",
    continentTab: "Continentes",
    toolsTab: "Ferramentas",
    quizStreak: "🔥 Sequência de {{count}}",
    quizHint: "Dica (restam {{count}})",
    quizNoHints: "Nenhuma dica restante",
    quizReviewAnswers: "Rever Respostas",
    quizBackToSummary: "Voltar ao Resumo",
    quizReviewTitle: "Revisão do Quiz",
    quizYourAnswer: "Sua resposta:",
    quizCorrectAnswer: "Resposta correta:",
    continentHint: "Dica: O país fica em {{continent}}.",
    quizBestStreak: "Melhor Sequência",
    quizAccuracy: "Precisão",
    quizRank: "Sua Classificação",
    rankNovice: "Iniciante em Bandeiras",
    rankApprentice: "Aprendiz de Bandeiras",
    rankAdept: "Adepto em Vexilologia",
    rankExpert: "Expert em Bandeiras",
    rankMaster: "Gênio da Geografia",
    quiz5050Hint: "50:50 (restam {{count}})",
    quizNo5050Hints: "Nenhuma 50:50 restante",
    quizCorrect: "Corretas",
    quizIncorrect: "Incorretas",
    sortBy: "Ordenar por",
    sortNameAsc: "Nome (A-Z)",
    sortNameDesc: "Nome (Z-A)",
    sortPopAsc: "População (Baixa-Alta)",
    sortPopDesc: "População (Alta-Baixa)",
    sortAreaAsc: "Área (Baixa-Alta)",
    sortAreaDesc: "Área (Alta-Baixa)",
    selectACountry: "Selecione um País",
    discoverIntro: "Mergulhe fundo no mundo da vexilologia. Explore temas comuns, designs únicos e o rico simbolismo presente nas bandeiras do mundo.",
    uniqueFlags: "Bandeiras Únicas",
    uniqueFlagOfTheDayTitle: "Bandeira Única do Dia",
    nepalFlag: "Nepal",
    nepalFlagDesc: "A única bandeira nacional não quadrilateral do mundo.",
    switzerlandFlag: "Suíça",
    switzerlandFlagDesc: "Uma das duas únicas bandeiras de estados soberanos com formato quadrado (a outra é a do Vaticano).",
    vaticanFlag: "Cidade do Vaticano",
    vaticanFlagDesc: "Uma das duas únicas bandeiras de estados soberanos com formato quadrado (a outra é a da Suíça).",
    symbolism: "Símbolos Comuns",
    sunSymbol: "Sol",
    sunSymbolDesc: "Representa unidade, vida e energia. Destaca-se nas bandeiras do Japão e da Argentina.",
    moonSymbol: "Lua / Crescente",
    moonSymbolDesc: "Frequentemente representa divindade e é um símbolo chave em muitas nações de maioria muçulmana como a Turquia.",
    crossSymbol: "Cruz",
    crossSymbolDesc: "Um símbolo do Cristianismo, central no design de muitas bandeiras europeias, especialmente na Escandinávia.",
    starsSymbol: "Estrelas",
    starsSymbolDesc: "Podem representar estados (EUA), constelações (Brasil) ou aspirações (China).",
    filterByColor: "Filtrar por Cor",
    colorsTab: "Cores",
    flagFactsTitle: "Vignetas de Vexilologia",
    showAnotherFact: "Mostrar outro fato",
    flagFactsList: JSON.stringify([
      "O estudo das bandeiras é chamado de **vexilologia**. O termo foi cunhado em 1957 pelo estudioso americano Whitney Smith.",
      "A bandeira das Filipinas é hasteada com a faixa vermelha para cima em tempos de guerra e a faixa azul para cima em tempos de paz.",
      "A bandeira do Paraguai é única porque tem emblemas diferentes na frente (anverso) e no verso (reverso).",
      "A única bandeira nacional que consistiu em uma única cor foi a da Líbia de 1977 a 2011, que era inteiramente verde.",
      "A Union Jack do Reino Unido é uma combinação de três bandeiras: a Cruz de São Jorge (Inglaterra), o Sautor de Santo André (Escócia) e o Sautor de São Patrício (Irlanda).",
      "A bandeira da Dinamarca, a Dannebrog, é a bandeira nacional em uso contínuo mais antiga do mundo, datando de 1219.",
      "Uma bandeira branca é um símbolo internacionalmente reconhecido de trégua, cessar-fogo e rendição.",
      "A bandeira de Moçambique é a única bandeira nacional a apresentar um fuzil de assalto moderno, um AK-47."
    ])
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const savedLang = localStorage.getItem('language') as Language;
        return savedLang || 'en';
    });

    const setLanguage = (lang: Language) => {
        localStorage.setItem('language', lang);
        setLanguageState(lang);
    };

    const t = useCallback((key: string, replacements?: { [key: string]: string }) => {
        let translation = translations[language][key] || key;
        if (replacements) {
            Object.keys(replacements).forEach(placeholder => {
                translation = translation.replace(`{{${placeholder}}}`, replacements[placeholder]);
            });
        }
        return translation;
    }, [language]);
    
    useEffect(() => {
        document.documentElement.lang = language;
        document.title = t('title');
    }, [language, t]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
