
import React, { createContext, useState, useContext, ReactNode, useEffect, useCallback } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string, replacements?: { [key: string]: string }) => string;
}

const translations: { [lang in Language]: { [key: string]: string } } = {
  en: {
    // ... existing translations ...
    achVexScholarTitle: "Vexillological Scholar",
    achVexScholarDesc: "Analyze details of 200 unique national designs.",
    achQuizVeteranTitle: "Quiz Veteran",
    achQuizVeteranDesc: "Complete 100 full quizzes across any game mode.",
    achStreakGodTitle: "Vexillology God",
    achStreakGodDesc: "Reach an incredible streak of 50 correct answers in a row.",
    achCollectionMasterTitle: "Grand Global Patron",
    achCollectionMasterDesc: "Collect 75 favorite flags in your personal registry.",
    achDesignLegendTitle: "Legendary Herald",
    achDesignLegendDesc: "Master the design studio by creating 50 unique flags.",
    achCuriousMindTitle: "Curious Mind",
    achCuriousMindDesc: "Engage with Vexy Gemini by asking 5 insightful questions.",
    achAIExpertTitle: "AI Specialist",
    achAIExpertDesc: "Request 25 deep dives from Vexy Gemini's knowledge base.",
    achAnalystTitle: "Comparative Analyst",
    achAnalystDesc: "Analyze and compare 10 pairs of flags side-by-side.",
    achMasterAnalystTitle: "Grand Master of Analysis",
    achMasterAnalystDesc: "Conduct 50 meticulous side-by-side comparisons.",
    // Rest of strings mapped correctly...
    title: "World Flag Explorer",
    headerTitle: "World Flags",
    explorer: "Explore",
    exploreTitle: "Flag of the Day",
    exploreSubtitle: "Uncover the history, symbolism, and vibrant colors behind the world's national flags. Use our filters to navigate the global tapestry of heraldry.",
    searchPlaceholder: "Search by country name or code...",
    fetchError: "Failed to retrieve country data. Please try again later.",
    api_fetch_error: "Connection error: Unable to load flag data.",
    errorOops: "Something went wrong",
    noResults: "No flags match your current search criteria.",
    noFlagsFound: "No Flags Found",
    noFlagsFoundDescription: "Try adjusting your filters or search term to discover more nations.",
    viewDetailsFor: "View details for {{countryName}}",
    flagOf: "Flag of {{country}}",
    closeModal: "Close",
    continents: "Continent",
    capital: "Capital",
    population: "Population",
    area: "Total Area",
    areaUnit: "km²",
    coatOfArms: "Coat of Arms",
    viewOnMap: "Locate on Google Maps",
    goToTop: "Back to top",
    footerRights: `© ${new Date().getFullYear()} World Flag Explorer. All rights reserved.`,
    footerBuiltWith: "Powered by React & Tailwind CSS | Data provided by REST Countries",
    showingFlags: "Displaying {{count}} of {{total}} flags",
    loadingFlags: "Loading global registry...",
    startQuiz: "Launch Quiz",
    quizTitle: "Vexillology Quiz",
    questionOf: "Question {{current}} of {{total}}",
    whichCountry: "To which country does this flag belong?",
    whichFlag: "Which of these is the flag of {{country}}?",
    nextQuestion: "Continue",
    quizResults: "Performance Summary",
    yourScore: "Accuracy: {{score}} / {{total}}",
    playAgain: "New Game",
    backToExplorer: "Return to Gallery",
    scoreFeedbackExcellent: "Masterful! Your knowledge of flags is world-class.",
    scoreFeedbackGood: "Impressive work! You have a strong grasp of global flags.",
    scoreFeedbackAverage: "Good effort! A bit more exploration and you'll be an expert.",
    scoreFeedbackPoor: "A great start! Keep exploring to unlock the secrets of vexillology.",
    discoverTitle: "Discover",
    discoverIntro: "Deep dive into the fascinating world of vexillology. Explore curated collections, unique designs, and rich global symbolism.",
    discoverLoading: "Curating a new collection for you...",
    flagOfTheDay: "Flag of the Day",
    flagOfTheDayLoading: "Selecting today's highlight...",
    filterAndSearch: "Search & Filter",
    filterByContinent: "By Continent",
    quizSetupTitle: "Quiz Center",
    chooseMode: "Select Challenge Mode",
    selectDifficulty: "Set Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Standard",
    difficultyHard: "Expert",
    difficultyEasyDesc: "Focuses on the most populous and well-known nations.",
    difficultyMediumDesc: "A balanced mix of nations from all corners of the globe.",
    difficultyHardDesc: "Challenge yourself with lesser-known and remote territories.",
    modeFlagToCountry: "Flag ➞ Country",
    modeFlagToCountryDesc: "Identify the nation associated with the flag.",
    modeCountryToFlag: "Country ➞ Flag",
    modeCountryToFlagDesc: "Select the correct flag for the given nation.",
    modeFlagToCapital: "Flag ➞ Capital",
    modeFlagToCapitalDesc: "Name the capital city based on the national flag.",
    modeCountryToCapital: "Country ➞ Capital",
    modeCountryToCapitalDesc: "Match the sovereign state with its capital city.",
    whichCapitalForCountry: "What is the capital city of {{country}}?",
    modeShapeToCountry: "Heraldry ➞ Country",
    modeShapeToCountryDesc: "Identify the nation by its official Coat of Arms.",
    whichCapital: "What is the capital of this country?",
    whichCoatOfArms: "Which nation's Coat of Arms is displayed here?",
    modeFlagle: "Flagle (Pixel Challenge)",
    modeFlagleDesc: "Guess the nation hidden behind a pixelated flag.",
    modeOddOneOut: "The Intruder",
    modeOddOneOutDesc: "Find the flag that doesn't belong to the region.",
    whichIsTheOddOneOut: "Which flag is the odd one out?",
    backToMenu: "Exit to Menu",
    quizTime: "Elapsed Time",
    quizAvgTime: "Average Pace",
    quizSeconds: "{{seconds}}s",
    compareMode: "Comparison Engine",
    compareModeTooltip: "Enable to select and compare two flags side-by-side",
    exitCompareMode: "Exit Comparison",
    selectForComparison: "Select {{countryName}} for side-by-side view",
    compareFlags: "Compare ({{count}}/2)",
    clearSelection: "Reset",
    comparisonTitle: "Flag Comparison Analysis",
    favorites: "My Collection",
    noFavorites: "Your collection is empty",
    noFavoritesDescription: "Mark flags with a heart to save them to your personal favorites.",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    addedToFavoritesToast: "{{countryName}} saved to favorites.",
    removedFromFavoritesToast: "{{countryName}} removed from favorites.",
    toggleTheme: "Toggle Light/Dark mode",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    continentTab: "Regions",
    toolsTab: "Utilities",
    quizStreak: "🔥 {{count}} Correct Streak",
    quizHint: "Hint ({{count}} remaining)",
    quizNoHints: "No hints available",
    quizReviewAnswers: "Analyze Performance",
    quizBackToSummary: "Back to Results",
    quizReviewTitle: "Detailed Review",
    quizYourAnswer: "Your selection:",
    quizCorrectAnswer: "Correct answer:",
    continentHint: "Regional Clue: Located in {{continent}}.",
    quizBestStreak: "Highest Streak",
    quizAccuracy: "Accuracy Rate",
    quizRank: "Acheived Rank",
    rankNovice: "Flag Novice",
    rankApprentice: "Heraldry Apprentice",
    rankAdept: "Vexillology Adept",
    rankExpert: "Flag Specialist",
    rankMaster: "Global Vexillologist",
    quiz5050Hint: "50:50 ({{count}} remaining)",
    quizNo5050Hints: "50:50 exhausted",
    quizCorrect: "Correct",
    quizIncorrect: "Incorrect",
    sortBy: "Order by",
    sortNameAsc: "Name (A-Z)",
    sortNameDesc: "Name (Z-A)",
    sortPopAsc: "Population (Increasing)",
    sortPopDesc: "Population (Decreasing)",
    sortAreaAsc: "Area (Increasing)",
    sortAreaDesc: "Area (Decreasing)",
    selectACountry: "Select a Nation",
    uniqueFlags: "Notable Designs",
    uniqueFlagOfTheDayTitle: "Design Highlight of the Day",
    flagFactsTitle: "Vexillological Insights",
    showAnotherFact: "Next Insight",
    achievementsSubtitle: "Monitor your progress and milestones in global exploration.",
    symbolismExplorerTitle: "Symbolism Engine",
    symbolSun: "Celestial Sun",
    symbolCrescent: "Lunar Crescent",
    symbolCross: "Heraldic Cross",
    symbolStar: "Astral Star",
    symbolAnimal: "Fauna & Wildlife",
    symbolWeapon: "Defense & Arms",
    symbolMap: "Cartography",
    symbolBuilding: "Architecture",
    noFlagsForSymbol: "No matches found for this symbol category.",
    achievementUnlocked: "Milestone Achieved!",
    progress: "Current Progress",
    newBadge: "NEW",
    level: "Level",
    xp: "XP",
    nextLevelAt: "Next Level at {{xp}} XP",
    totalXP: "Total Experience",
    vexMastery: "Vexillology Mastery",
    flagsViewed: "Flags Viewed",
    perfectQuizzes: "Perfect Quizzes",
    maxStreak: "Max Streak",
    designs: "Designs",
    rarityCommon: "Common",
    rarityRare: "Rare",
    rarityEpic: "Epic",
    rarityLegendary: "Legendary",
    cat_explorer: "Global Voyager",
    cat_quiz: "Intellectual Master",
    cat_collector: "Vexillology Curator",
    cat_designer: "Creative Visionary",
    achFirstStepsTitle: "Inaugural Discovery",
    achFirstStepsDesc: "Explore your very first national flag.",
    achWorldTravelerTitle: "Global Wayfarer",
    achWorldTravelerDesc: "Uncover the details of 50 unique flags.",
    achCenturyClubTitle: "Century Explorer",
    achCenturyClubDesc: "Reach the milestone of 100 flags explored.",
    achVexExpertTitle: "Vexillology Authority",
    achVexExpertDesc: "Deep dive into 150 different national designs.",
    achMasterExplorerTitle: "Sovereign of Earth",
    achMasterExplorerDesc: "Complete the global registry by viewing all 240+ flags.",
    achQuizStarterTitle: "Academic Pursuit",
    achQuizStarterDesc: "Successfully complete your first knowledge challenge.",
    achQuizScholarTitle: "Active Scholar",
    achQuizScholarDesc: "Demonstrate consistency by completing 10 full quizzes.",
    achQuizMarathonerTitle: "Knowledge Marathoner",
    achQuizMarathonerDesc: "A true academic! Complete 50 quizzes across any mode.",
    achPerfectScoreTitle: "Flawless Execution",
    achPerfectScoreDesc: "Achieve 100% accuracy in any quiz challenge.",
    achPerfectLegendTitle: "Immaculate Legend",
    achPerfectLegendDesc: "Achieve 10 perfect scores. True perfection is rare.",
    achStreakMasterTitle: "Unstoppable Momentum",
    achStreakMasterDesc: "Maintain a streak of 10 consecutive correct answers.",
    achStreakGodlikeTitle: "Vexillology God",
    achStreakGodlikeDesc: "Reach an incredible streak of 25 correct answers in a row.",
    achCuratorTitle: "Registry Curator",
    achCuratorDesc: "Build a personal collection of 10 favorite flags.",
    achCollectorProTitle: "Passionate Collector",
    achCollectorProDesc: "Grow your private flag collection to 25 entries.",
    achWorldCuratorTitle: "Grand Global Curator",
    achWorldCuratorDesc: "Collect 50 favorite flags. You have the world in your hands.",
    achArtistTitle: "Heraldic Designer",
    achArtistDesc: "Create and export your own unique flag design.",
    achProlificDesignerTitle: "Prolific Creator",
    achProlificDesignerDesc: "Master the patterns and layouts by creating 10 designs.",
    achDesignVisionaryTitle: "Master of Tinctures",
    achDesignVisionaryDesc: "Establish yourself as a master by creating 30 unique designs.",
    dataManagement: "Progress Management",
    exportData: "Export Progress",
    importData: "Import Progress",
    resetData: "Reset All Progress",
    resetConfirm: "Are you sure? This will wipe your levels and achievements forever.",
    dataImported: "Progress successfully restored!",
    dataExported: "Backup file generated.",
    flagFactsList: "[\"**Nepal** is the only sovereign nation with a non-quadrilateral flag design.\", \"The flag of **Denmark** holds the record as the oldest national flag in continuous use, dating back to 1219.\", \"**Jamaica** is currently the only national flag that does not feature the colors red, white, or blue.\", \"**Switzerland** and **Vatican City** are the only two states with officially square national flags.\", \"The flag of **Mozambique** is the only one to feature a modern assault rifle, representing national defense.\", \"**Belize** is unique for having a national flag that features human figures as a central element.\", \"The **Philippines** flag is unique: it is flown upside down (red stripe on top) during times of official war.\", \"**Libya** previously held the record for the only solid-color national flag (pure green).\", \"The celestial bodies on **Nepal's** flag symbolize the hope for national longevity alongside the sun and moon.\", \"The colors of the **South African** flag represent unity and diversity in the wake of its history.\"]",
    mapTitle: "Global Cartography",
    mapSubtitle: "Navigate the world through geography and location.",
    mapComingSoon: "Geographical Navigator",
    mapModeInstructions: "Use the map to browse countries by location. Tap a country tag to reveal its full flag and statistical profile.",
    nepalFlagDesc: "The world's only non-quadrilateral national flag.",
    switzerlandFlagDesc: "A perfectly square design, rare among sovereign states.",
    vaticanFlagDesc: "The second of only two officially square national flags.",
    paraguayFlagDesc: "Unique for having different emblems on the front and back.",
    denmarkFlagDesc: "Recognized as the world's oldest continuously used flag.",
    philippinesFlagDesc: "A flag that signals war when flown inverted.",
    mozambiqueFlagDesc: "A modern design featuring a kalashnikov for defense.",
    qatarFlagDesc: "The only national flag with a width more than twice its height.",
    belizeFlagDesc: "Distinguished by the inclusion of human figures in its seal.",
    cyprusFlagDesc: "One of the few flags to feature a literal map of the nation.",
    brazilFlagDesc: "A celestial snapshot of the sky over Rio on Nov 15, 1889.",
    austriaFlagDesc: "Rooted in legend, among the oldest designs in Europe.",
    lesothoFlagDesc: "Features the 'Mokorotlo', a traditional Basotho hat.",
    cambodiaFlagDesc: "The only national flag to feature a building (Angkor Wat).",
    turkmenistanFlagDesc: "Considered the most complex and detailed flag design.",
    sriLankaFlagDesc: "The 'Lion Flag', symbolizing bravery and the nation's origins.",
    canadaFlagDesc: "The iconic Maple Leaf, a symbol of nature and identity.",
    southAfricaFlagDesc: "A vibrant 'Rainbow Nation' design adopted in 1994.",
    dominicanRepublicFlagDesc: "The only national flag featuring an open Bible.",
    jamaicaFlagDesc: "A unique design free from red, white, and blue colors.",
    norwayFlagDesc: "Often called the 'Mother of all flags' due to hidden designs within.",
    ugandaFlagDesc: "Centrally features the Grey Crowned Crane, a symbol of gentleness.",
    bhutanFlagDesc: "Features the Thunder Dragon (Druk) from local mythology.",
    libyaFlagDesc: "Now featuring the crescent, formerly a solid green field.",
    saudiArabiaFlagDesc: "The only flag never flown at half-mast due to the sacred creed.",
    kiribatiFlagDesc: "A literal representation of the archipelago's location.",
    dominicaFlagDesc: "Features the Sisserou Parrot, a bird unique to the island.",
    eswatiniFlagDesc: "Displays the shield and spears of the Emasotsha regiment.",
    southKoreaFlagDesc: "Centered on the 'Taegeuk', representing cosmic balance.",
    lebanonFlagDesc: "Features the Cedar, a symbol of holiness and eternity.",
    kenyaFlagDesc: "The Maasai shield symbolizes the defense of national freedom.",
    grenadaFlagDesc: "The 'Spice Isle', featuring a nutmeg clove on its hoist.",
    mexicoFlagDesc: "Based on the Aztec legend of the founding of Tenochtitlan.",
    kyrgyzstanFlagDesc: "The sun's 40 rays represent the 40 original Kyrgyz tribes.",
    antiguaBarbudaFlagDesc: "Symbolizing a new era (sun) and African heritage (black).",
    seychellesFlagDesc: "Radiating bands symbolize a dynamic country moving forward.",
    vanuatuFlagDesc: "The boar's tusk symbolizes wealth and traditional peace.",
    eritreaFlagDesc: "The olive branch wreath symbolizes hard-won autonomy.",
    filterByColor: "Filter by Tincture",
    showingFlagsWith: "Designs featuring {{color}}",
    noFlagsForColor: "No designs match this specific tincture.",
    bicolorHorizontal: "Horizontal Bicolor",
    bicolorVertical: "Vertical Bicolor",
    tricolorHorizontal: "Horizontal Tricolor",
    tricolorVertical: "Vertical Tricolor",
    nordicCross: "Nordic Cross",
    noSymbol: "No Emblem",
    star: "Astral Star",
    circle: "Orb/Circle",
    mainColor: "Primary Field",
    crossColor: "Cross Tincture",
    colorN: "Tincture {{n}}",
    flagDesignerTitle: "Heraldry Workshop",
    flagDesignerSubtitle: "Compose your own unique flag using traditional vexillological patterns and symbols.",
    layout: "Structural Layout",
    colors: "Color Palette",
    symbol: "Central Emblem",
    symbolColor: "Emblem Tincture",
    actions: "Management",
    randomize: "Generate Random",
    download: "Export SVG",
    guessTheFlag: "Mystery Flag",
    guessesLeft: "{{count}} attempts remaining",
    congratulations: "Victory!",
    gameOver: "Challenge Ended",
    correctAnswerWas: "The correct identity was {{country}}",
    nextFlagIn: "Next challenge in",
    enterCountryName: "Type nation name...",
    all: "Complete Registry",
    allQuestions: "All Available Questions",
    numberOfQuestions: "{{count}} Questions",
    selectNumberOfQuestions: "Define Session Length",
    combo: "COMBO X{{n}}",
    timeLeft: "{{n}}s",
    speedBonus: "Speed Bonus: +{{n}}",
    outOfTime: "Time Expired!",
    explored: "Explored",
    addToComparison: "Add to Comparison",
    removeFromComparison: "Remove from Comparison",
    guessesLabel: "GUESSES",
    excellentLabel: "EXCELLENT!",
    youWonLabel: "YOU WON!",
    correctAnswerWasLabel: "The flag was from",
    hintNameStarts: "Hint: The name starts with",
    hintRegion: "Hint: Located in region:",
    hitsLabel: "HITS",
    questionLabel: "Question"
  },
  pt: {
    achVexScholarTitle: "Erudito Vexilológico",
    achVexScholarDesc: "Analise os detalhes de 200 designs nacionais únicos.",
    achQuizVeteranTitle: "Veterano dos Quizzes",
    achQuizVeteranDesc: "Complete 100 quizzes em qualquer modo de jogo.",
    achStreakGodTitle: "Semideus da Vexilologia",
    achStreakGodDesc: "Alcance uma sequência incrível de 50 acertos seguidos.",
    achCollectionMasterTitle: "Grande Patrono Global",
    achCollectionMasterDesc: "Colecione 75 bandeiras favoritas no seu registro pessoal.",
    achDesignLegendTitle: "Arauto Lendário",
    achDesignLegendDesc: "Domine o estúdio de design criando 50 bandeiras únicas.",
    achCuriousMindTitle: "Mente Curiosa",
    achCuriousMindDesc: "Interaja com o Vexy Gemini fazendo 5 perguntas perspicazes.",
    achAIExpertTitle: "Especialista em IA",
    achAIExpertDesc: "Solicite 25 análises profundas da base de conhecimento do Vexy.",
    achAnalystTitle: "Analista Comparativo",
    achAnalystDesc: "Analise e compare 10 pares de bandeiras lado a lado.",
    achMasterAnalystTitle: "Grão-Mestre da Análise",
    achMasterAnalystDesc: "Realize 50 comparações detalhadas lado a lado.",
    // Correct mappings...
    title: "Explorador de Bandeiras",
    headerTitle: "Bandeiras do Mundo",
    explorer: "Explorar",
    exploreTitle: "Bandeira do Dia",
    exploreSubtitle: "Descubra a história, o simbolismo e as cores vibrantes por trás das bandeiras das nações. Utilize nossos filtros para navegar pela rica tapeçaria da heráldica global.",
    searchPlaceholder: "Pesquise por nome ou sigla...",
    fetchError: "Não foi possível obter os dados. Tente novamente em instantes.",
    api_fetch_error: "Erro de conexão: Não foi possível carregar os dados das bandeiras.",
    errorOops: "Algo deu errado",
    noResults: "Nenhuma bandeira corresponde aos critérios atuais.",
    noFlagsFound: "Nenhuma Bandeira Encontrada",
    noFlagsFoundDescription: "Tente ajustar seus filtros ou termos de busca para descobrir novas nações.",
    viewDetailsFor: "Ver detalhes de {{countryName}}",
    flagOf: "Bandeira de {{country}}",
    closeModal: "Fechar",
    continents: "Continente",
    capital: "Capital",
    population: "População",
    area: "Área Total",
    areaUnit: "km²",
    coatOfArms: "Brasão de Armas",
    viewOnMap: "Localizar no Google Maps",
    goToTop: "Voltar ao topo",
    footerRights: `© ${new Date().getFullYear()} Explorador de Bandeiras. Todos os direitos reservados.`,
    footerBuiltWith: "Desenvolvido com React & Tailwind CSS | Dados via REST Countries",
    showingFlags: "Exibindo {{count}} de {{total}} bandeiras",
    loadingFlags: "Carregando registro global...",
    startQuiz: "Iniciar Desafio",
    quizTitle: "Quiz Vexilológico",
    questionOf: "Questão {{current}} de {{total}}",
    whichCountry: "A qual país pertence esta bandeira?",
    whichFlag: "Qual destas é a bandeira de {{country}}?",
    nextQuestion: "Continuar",
    quizResults: "Resumo de Desempenho",
    yourScore: "Precisão: {{score}} / {{total}}",
    playAgain: "Novo Jogo",
    backToExplorer: "Voltar à Galeria",
    scoreFeedbackExcellent: "Magistral! Seu conhecimento é de um verdadeiro especialista.",
    scoreFeedbackGood: "Trabalho impressionante! Você conhece muito bem o mapa-múndi.",
    scoreFeedbackAverage: "Bom esforço! Mais algumas rodadas e você será um expert.",
    scoreFeedbackPoor: "Um ótimo começo! Continue explorando para dominar a vexilologia.",
    discoverTitle: "Descobrir",
    discoverIntro: "Mergulhe no fascinante universo da vexilologia. Explore coleções curadas, designs únicos e o rico simbolismo global.",
    discoverLoading: "Preparando uma nova coleção para você...",
    flagOfTheDay: "Bandeira do Dia",
    flagOfTheDayLoading: "Selecionando o destaque de hoje...",
    filterAndSearch: "Busca & Filtros",
    filterByContinent: "Por Continente",
    quizSetupTitle: "Centro de Desafios",
    chooseMode: "Escolha o Modo de Jogo",
    selectDifficulty: "Nível de Dificuldade",
    difficultyEasy: "Iniciante",
    difficultyMedium: "Padrão",
    difficultyHard: "Especialista",
    difficultyEasyDesc: "Focado nas nações mais populosas e conhecidas mundialmente.",
    difficultyMediumDesc: "Uma mistura equilibrada de países de todos os cantos do globo.",
    difficultyHardDesc: "Dasafio-se com territórios remotos e nações menos conhecidas.",
    modeFlagToCountry: "Bandeira ➞ País",
    modeFlagToCountryDesc: "Identifique a nação associada à bandeira exibida.",
    modeCountryToFlag: "País ➞ Bandeira",
    modeCountryToFlagDesc: "Selecione a bandeira correta para a nação indicada.",
    modeFlagToCapital: "Bandeira ➞ Capital",
    modeFlagToCapitalDesc: "Identifique a capital com base na bandeira nacional.",
    modeCountryToCapital: "País ➞ Capital",
    modeCountryToCapitalDesc: "Relacione o estado soberano à sua respectiva capital.",
    whichCapitalForCountry: "Qual é a capital de {{country}}?",
    modeShapeToCountry: "Heráldica ➞ País",
    modeShapeToCountryDesc: "Identifique a nação através do seu Brasão de Armas oficial.",
    whichCapital: "Qual é a capital deste país?",
    whichCoatOfArms: "De qual nação é este Brasão de Armas?",
    modeFlagle: "Flagle (Desafio Pixelado)",
    modeFlagleDesc: "Adivinhe o país oculto por trás de uma bandeira em baixa resolução.",
    modeOddOneOut: "O Intruso",
    modeOddOneOutDesc: "Encontre a bandeira que não pertence à região exibida.",
    whichIsTheOddOneOut: "Qual destas bandeiras é a intrusa?",
    backToMenu: "Sair para o Menu",
    quizTime: "Tempo Decorrido",
    quizAvgTime: "Ritmo Médio",
    quizSeconds: "{{seconds}}s",
    compareMode: "Motor de Comparação",
    compareModeTooltip: "Ative para selecionar e comparar duas bandeiras lado a lado",
    exitCompareMode: "Sair da Comparação",
    selectForComparison: "Selecionar {{countryName}} para análise comparativa",
    compareFlags: "Comparar ({{count}}/2)",
    clearSelection: "Reiniciar",
    comparisonTitle: "Análise Comparativa de Bandeiras",
    favorites: "Minha Coleção",
    noFavorites: "Sua coleção está vazia",
    noFavoritesDescription: "Marque bandeiras com um coração para salvá-las na sua coleção pessoal.",
    addToFavorites: "Adicionar aos favoritos",
    removeFromFavorites: "Remover dos favoritos",
    addedToFavoritesToast: "{{countryName}} adicionado aos favoritos.",
    removedFromFavoritesToast: "{{countryName}} removido dos favoritos.",
    toggleTheme: "Alternar modo Claro/Escuro",
    scrollLeft: "Rolar para esquerda",
    scrollRight: "Rolar para direita",
    continentTab: "Regiões",
    toolsTab: "Utilitários",
    quizStreak: "🔥 Sequência de {{count}} Acertos",
    quizHint: "Dica (restam {{count}})",
    quizNoHints: "Sem dicas disponíveis",
    quizReviewAnswers: "Analisar Desempenho",
    quizBackToSummary: "Voltar aos Resultados",
    quizReviewTitle: "Revisão Detalhada",
    quizYourAnswer: "Sua seleção:",
    quizCorrectAnswer: "Resposta correta:",
    continentHint: "Pista Regional: Localizado em {{continent}}.",
    quizBestStreak: "Maior Sequência",
    quizAccuracy: "Taxa de Acerto",
    quizRank: "Patente Alcançada",
    rankNovice: "Novato em Bandeiras",
    rankApprentice: "Aprendiz de Heráldica",
    rankAdept: "Adepto da Vexilologia",
    rankExpert: "Especialista em Bandeiras",
    rankMaster: "Vexilologista Global",
    quiz5050Hint: "50:50 (restam {{count}})",
    quizNo5050Hints: "50:50 esgotado",
    quizCorrect: "Correto",
    quizIncorrect: "Incorreto",
    sortBy: "Ordenar por",
    sortNameAsc: "Nome (A-Z)",
    sortNameDesc: "Nome (Z-A)",
    sortPopAsc: "População (Crescente)",
    sortPopDesc: "População (Decrescente)",
    sortAreaAsc: "Área (Crescente)",
    sortAreaDesc: "Área (Decrescente)",
    selectACountry: "Selecione uma Nação",
    uniqueFlags: "Designs Notáveis",
    uniqueFlagOfTheDayTitle: "Destaque de Design do Dia",
    flagFactsTitle: "Curiosidades Vexilológicas",
    showAnotherFact: "Próxima Curiosidade",
    achievementsSubtitle: "Acompanhe seu progresso e marcos na exploração global.",
    symbolismExplorerTitle: "Motor de Simbolismo",
    symbolSun: "Sol Celestial",
    symbolCrescent: "Crescente Lunar",
    symbolCross: "Cruz Heráldica",
    symbolStar: "Estrela Astral",
    symbolAnimal: "Fauna e Vida Selvagem",
    symbolWeapon: "Defesa e Armas",
    symbolMap: "Cartografia",
    symbolBuilding: "Arquitetura",
    noFlagsForSymbol: "Nenhum resultado para esta categoria de símbolo.",
    achievementUnlocked: "Marco Alcançado!",
    progress: "Progresso Atual",
    newBadge: "NOVO",
    level: "Nível",
    xp: "XP",
    nextLevelAt: "Próximo nível em {{xp}} XP",
    totalXP: "Experiência Total",
    vexMastery: "Domínio Vexilológico",
    flagsViewed: "Bandeiras Vistas",
    perfectQuizzes: "Quizzes Perfeitos",
    maxStreak: "Melhor Sequência",
    designs: "Designs Criados",
    rarityCommon: "Comum",
    rarityRare: "Rara",
    rarityEpic: "Épica",
    rarityLegendary: "Lendária",
    cat_explorer: "Viajante Global",
    cat_quiz: "Mestre Intelectual",
    cat_collector: "Curador de Bandeiras",
    cat_designer: "Visionário Criativo",
    achFirstStepsTitle: "Descoberta Inaugural",
    achFirstStepsDesc: "Explore sua primeira bandeira nacional.",
    achWorldTravelerTitle: "Andarilho do Mundo",
    achWorldTravelerDesc: "Descubra os detalhes de 50 bandeiras únicas.",
    achCenturyClubTitle: "Explorador do Século",
    achCenturyClubDesc: "Alcance o marco de 100 bandeiras exploradas.",
    achVexExpertTitle: "Autoridade em Vexilologia",
    achVexExpertDesc: "Analise profundamente 150 designs nacionais diferentes.",
    achMasterExplorerTitle: "Soberano da Terra",
    achMasterExplorerDesc: "Complete o registro global visualizando todas as mais de 240 bandeiras.",
    achQuizStarterTitle: "Jornada Acadêmica",
    achQuizStarterDesc: "Conclua com sucesso seu primeiro desafio de conhecimento.",
    achQuizScholarTitle: "Estudioso Ativo",
    achQuizScholarDesc: "Demonstre consistência completando 10 quizzes completos.",
    achQuizMarathonerTitle: "Maratonista do Saber",
    achQuizMarathonerDesc: "Um verdadeiro acadêmico! Complete 50 quizzes em qualquer modo.",
    achPerfectScoreTitle: "Execução Impecável",
    achPerfectScoreDesc: "Alcance 100% de precisão em qualquer desafio do quiz.",
    achPerfectLegendTitle: "Lenda Imaculada",
    achPerfectLegendDesc: "Alcance 10 pontuações perfeitas. A perfeição real é rara.",
    achStreakMasterTitle: "Momento Imparável",
    achStreakMasterDesc: "Mantenha uma sequência de 10 acertos consecutivos.",
    achStreakGodlikeTitle: "Deus da Vexilologia",
    achStreakGodlikeDesc: "Alcance uma sequência incrível de 25 acertos seguidos.",
    achCuratorTitle: "Curador do Registro",
    achCuratorDesc: "Construa uma coleção pessoal com 10 bandeiras favoritas.",
    achCollectorProTitle: "Colecionador Apaixonado",
    achCollectorProDesc: "Aumente sua coleção privada para 25 bandeiras.",
    achWorldCuratorTitle: "Grande Curador Global",
    achWorldCuratorDesc: "Colecione 50 bandeiras favoritas. O mundo está em suas mãos.",
    achArtistTitle: "Designer Heráldico",
    achArtistDesc: "Crie e exporte seu próprio design exclusivo de bandeira.",
    achProlificDesignerTitle: "Criador Prolífico",
    achProlificDesignerDesc: "Domine os padrões e layouts criando 10 designs.",
    achDesignVisionaryTitle: "Mestre das Tinturas",
    achDesignVisionaryDesc: "Consagre-se como um mestre criando 30 designs únicos.",
    dataManagement: "Gerenciamento de Dados",
    exportData: "Exportar Progresso",
    importData: "Importar Progresso",
    resetData: "Resetar Todo o Progresso",
    resetConfirm: "Tem certeza? Isso apagará seus níveis e conquistas para sempre.",
    dataImported: "Progresso restaurado com sucesso!",
    dataExported: "Arquivo de backup gerado.",
    flagFactsList: "[\"O **Nepal** é a única nação soberana com uma bandeira nacional não quadrilátera.\", \"A bandeira da **Dinamarca** é reconhecida como a mais antiga em uso contínuo, datando de 1219.\", \"A **Jamaica** é atualmente a única bandeira nacional que não contém as cores vermelho, branco ou azul.\", \"A **Suíça** e o **Vaticano** são os únicos dois estados com bandeiras nacionais oficialmente quadradas.\", \"A bandeira de **Moçambique** é a única a apresentar um rifle de assalto moderno, simbolizando a defesa nacional.\", \"**Belize** destaca-se por ter a única bandeira nacional que apresenta figuras humanas como elemento central.\", \"A bandeira das **Filipinas** tem um uso único: é hasteada invertida (vermelho no topo) em tempos de guerra oficial.\", \"A **Líbia** já ostentou a única bandeira de cor sólida do mundo (totalmente verde).\", \"Os corpos celestes na bandeira do **Nepal** simbolizam a esperança de que a nação dure tanto quanto o sol e a lua.\", \"As cores da bandeira da **África do Sul** simbolizam a unidade e diversidade após sua reconstrução histórica.\"]",
    mapTitle: "Cartografia Global",
    mapSubtitle: "Navegue pelo mundo através da geografia e localização.",
    mapComingSoon: "Navegador Geográfico",
    mapModeInstructions: "Use o mapa para explorar países por localização. Toque na tag de um país para revelar sua bandeira e perfil estatístico.",
    nepalFlagDesc: "A única bandeira nacional não quadrilátera do mundo.",
    switzerlandFlagDesc: "Um design perfeitamente quadrado, raro entre estados soberanos.",
    vaticanFlagDesc: "A segunda de apenas duas bandeiras oficialmente quadradas.",
    paraguayFlagDesc: "Única por apresentar emblemas diferentes no anverso e no reverso.",
    denmarkFlagDesc: "Reconhecida como a bandeira mais antiga do mundo em uso contínuo.",
    philippinesFlagDesc: "Uma bandeira que sinaliza estado de guerra quando invertida.",
    mozambiqueFlagDesc: "Design moderno que apresenta uma kalashnikov para defesa.",
    qatarFlagDesc: "A única bandeira nacional com largura superior ao dobro de sua altura.",
    belizeFlagDesc: "Distingue-se pela inclusão de figuras humanas em seu selo oficial.",
    cyprusFlagDesc: "Uma das poucas bandeiras a exibir o mapa literal da própria nação.",
    brazilFlagDesc: "Um retrato do céu sobre o Rio de Janeiro em 15 de novembro de 1889.",
    austriaFlagDesc: "Baseada em lendas medievais, entre os designs mais antigos da Europa.",
    lesothoFlagDesc: "Exibe o 'Mokorotlo', um chapéu tradicional do povo Basoto.",
    cambodiaFlagDesc: "A única bandeira nacional a apresentar um edifício (Angkor Wat).",
    turkmenistanFlagDesc: "Considerada a bandeira com o design mais complexo e detalhado do mundo.",
    sriLankaFlagDesc: "A 'Bandeira do Leão', simbolizando a bravura e as origens da nação.",
    canadaFlagDesc: "A icônica Folha de Bordo, símbolo de natureza e identidade canadense.",
    southAfricaFlagDesc: "O design da 'Nação Arco-Íris', adotado oficialmente em 1994.",
    dominicanRepublicFlagDesc: "A única bandeira nacional que apresenta uma Bíblia aberta.",
    jamaicaFlagDesc: "Um design exclusivo, livre das cores vermelho, branco e azul.",
    norwayFlagDesc: "Frequentemente chamada de 'Mãe de todas as bandeiras' por conter outros designs ocultos.",
    ugandaFlagDesc: "Apresenta centralmente o Grou-coroado, símbolo de elegância e mansidão.",
    bhutanFlagDesc: "Exibe o Dragão do Trovão (Druk) da mitologia local.",
    libyaFlagDesc: "Atualmente com o crescente, anteriormente um campo verde sólido.",
    saudiArabiaFlagDesc: "A única bandeira nunca hasteada a meio-mastro devido ao seu credo sagrado.",
    kiribatiFlagDesc: "Uma representação literal da localização geográfica do arquipélago.",
    dominicaFlagDesc: "Apresenta o Papagaio-imperial, ave endêmica da ilha.",
    eswatiniFlagDesc: "Exibe o escudo e as lanças do regimento Emasotsha.",
    southKoreaFlagDesc: "Centrada no 'Taegeuk', representando o equilíbrio cósmico.",
    lebanonFlagDesc: "Apresenta o Cedro, símbolo de santidade e eternidade.",
    kenyaFlagDesc: "O escudo Maasai simboliza a prontidão na defesa da liberdade nacional.",
    grenadaFlagDesc: "A 'Ilha das Especiarias', exibindo um dente de noz-moscada em seu design.",
    mexicoFlagDesc: "Inspirada na lenda asteca sobre a fundação de Tenochtitlán.",
    kyrgyzstanFlagDesc: "Os 40 raios do sol representam as 40 tribos originais do Quirguistão.",
    antiguaBarbudaFlagDesc: "Simboliza uma nova era (sol) and a herança africana (preto).",
    seychellesFlagDesc: "Faixas radiantes simbolizam um país dinâmico em constante movimento.",
    vanuatuFlagDesc: "A presa de javali simboliza prosperidade e a paz tradicional.",
    eritreaFlagDesc: "A coroa de ramos de oliveira simboliza a autonomia conquistada.",
    filterByColor: "Filtrar por Tintura",
    showingFlagsWith: "Designs que utilizam {{color}}",
    noFlagsForColor: "Nenhum resultado para esta categoria de símbolo.",
    bicolorHorizontal: "Bicolor Horizontal",
    bicolorVertical: "Bicolor Vertical",
    tricolorHorizontal: "Tricolor Horizontal",
    tricolorVertical: "Tricolor Vertical",
    nordicCross: "Cruz Nórdica",
    noSymbol: "Sem Emblema",
    star: "Estrela Astral",
    circle: "Círculo/Orbe",
    mainColor: "Campo Primário",
    crossColor: "Tintura da Cruz",
    colorN: "Tintura {{n}}",
    flagDesignerTitle: "Oficina de Heráldica",
    flagDesignerSubtitle: "Componha sua própria bandeira utilizando padrões e símbolos tradicionais da vexilologia.",
    layout: "Estrutura do Layout",
    colors: "Paleta de Cores",
    symbol: "Emblema Central",
    symbolColor: "Tintura do Emblema",
    actions: "Gerenciamento",
    randomize: "Gerar Aleatória",
    download: "Exportar SVG",
    guessTheFlag: "Bandeira Mistério",
    guessesLeft: "{{count}} tentativas restantes",
    congratulations: "Vitória!",
    gameOver: "Desafio Encerrado",
    correctAnswerWas: "A identidade correta era {{country}}",
    nextFlagIn: "Próximo desafio em",
    enterCountryName: "Digite o nome da nação...",
    all: "Registro Completo",
    allQuestions: "Todas as Questões Disponíveis",
    numberOfQuestions: "{{count}} Questões",
    selectNumberOfQuestions: "Definir Duração da Sessão",
    combo: "COMBO X{{n}}",
    timeLeft: "{{n}}s",
    speedBonus: "Bônus de Velocidade: +{{n}}",
    outOfTime: "Tempo Expirado!",
    explored: "Explorado",
    addToComparison: "Adicionar à Comparação",
    removeFromComparison: "Remover da Comparação",
    guessesLabel: "PALPITES",
    excellentLabel: "EXCELENTE!",
    youWonLabel: "VOCÊ VENCEU!",
    correctAnswerWasLabel: "A bandeira era de",
    hintNameStarts: "Dica: O nome começa com",
    hintRegion: "Dica: Localizado na região:",
    hitsLabel: "ACERTOS",
    questionLabel: "Questão"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        if (saved === 'en' || saved === 'pt') return saved;
        return navigator.language.startsWith('pt') ? 'pt' : 'en';
    });

    const setLanguage = useCallback((lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
        document.documentElement.lang = lang;
    }, []);

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const t = useCallback((key: string, replacements?: { [key: string]: string }) => {
        let text = translations[language][key] || translations['en'][key] || key;
        
        if (replacements) {
            Object.entries(replacements).forEach(([k, v]) => {
                text = text.replace(`{{${k}}}`, v);
            });
        }
        
        return text;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
