
import React, { createContext, useState, useContext, ReactNode, useEffect, useCallback } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string, replacements?: { [key: string]: string }) => string;
}

const translations: { [lang in Language]: { [key: string]: string } } = {
  en: {
    title: "World Flag Explorer",
    headerTitle: "Flags of the World",
    explorer: "Explorer",
    exploreTitle: "Flag of the Day",
    exploreSubtitle: "Discover the stories, symbols and colors behind the flags of nations. Use the filters below to navigate the rich tapestry of global heraldry.",
    searchPlaceholder: "Search for country name...",
    fetchError: "Failed to fetch country data. Please try again later.",
    api_fetch_error: "Unable to load flag data. Please check your connection.",
    errorOops: "Oops! Something went wrong.",
    noResults: "No flags match your search criteria.",
    noFlagsFound: "No Flags Found",
    noFlagsFoundDescription: "Try adjusting your search or filter to find what you're looking for.",
    viewDetailsFor: "View details for {{countryName}}",
    flagOf: "Flag of {{country}}",
    closeModal: "Close modal",
    continents: "Continent(s)",
    capital: "Capital",
    population: "Population",
    area: "Area",
    areaUnit: "km²",
    coatOfArms: "Coat of Arms",
    viewOnMap: "View on Google Maps",
    goToTop: "Go to top",
    footerRights: `© ${new Date().getFullYear()} World Flag Explorer. All rights reserved.`,
    footerBuiltWith: "Built with React & Tailwind CSS | Data from REST Countries API",
    showingFlags: "Showing {{count}} of {{total}} flags",
    loadingFlags: "Loading flags from around the world...",
    startQuiz: "Start Quiz",
    quizTitle: "Quiz",
    questionOf: "Question {{current}} of {{total}}",
    whichCountry: "Which country does this flag belong to?",
    whichFlag: "Which flag belongs to {{country}}?",
    nextQuestion: "Next Question",
    quizResults: "Quiz Results",
    yourScore: "You got {{score}} out of {{total}}",
    playAgain: "Play Again",
    backToExplorer: "Back to Explorer",
    scoreFeedbackExcellent: "Excellent! You're a flag expert!",
    scoreFeedbackGood: "Good job! You know your flags well.",
    scoreFeedbackAverage: "Not bad! With a little more practice you'll be an expert.",
    scoreFeedbackPoor: "Keep practicing! The world of flags is fascinating.",
    discoverTitle: "Discover",
    discoverIntro: "Dive deep into the world of vexillology. Explore common themes, unique designs and the rich symbolism present in world flags.",
    discoverLoading: "Creating a new collection for you...",
    flagOfTheDay: "Flag of the Day",
    flagOfTheDayLoading: "Selecting today's featured flag...",
    filterAndSearch: "Filter and Search",
    filterByContinent: "Filter by Continent",
    quizSetupTitle: "Quiz Setup",
    chooseMode: "Choose a Game Mode",
    selectDifficulty: "Select Difficulty",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    difficultyEasyDesc: "Most populous countries.",
    difficultyMediumDesc: "A mix of all countries.",
    difficultyHardDesc: "Lesser-known countries.",
    modeFlagToCountry: "Flag ➞ Country",
    modeFlagToCountryDesc: "Guess the country by its flag.",
    modeCountryToFlag: "Country ➞ Flag",
    modeCountryToFlagDesc: "Find the correct flag for the country.",
    modeFlagToCapital: "Flag ➞ Capital",
    modeFlagToCapitalDesc: "Identify the capital by the flag.",
    modeCountryToCapital: "Country ➞ Capital",
    modeCountryToCapitalDesc: "Guess the country's capital.",
    whichCapitalForCountry: "What is the capital of {{country}}?",
    modeShapeToCountry: "Coat of Arms ➞ Country",
    modeShapeToCountryDesc: "Recognize the country by its coat of arms.",
    whichCapital: "To which capital city does this flag belong?",
    whichCoatOfArms: "Which country's coat of arms is this?",
    modeFlagle: "Flagle",
    modeFlagleDesc: "Guess the country from a pixelated flag.",
    modeOddOneOut: "Which one is the odd one out?",
    modeOddOneOutDesc: "Find the flag from a different region.",
    whichIsTheOddOneOut: "Which flag is the odd one out?",
    backToMenu: "Back to Menu",
    quizTime: "Total Time",
    quizAvgTime: "Avg Time / Q",
    quizSeconds: "{{seconds}}s",
    compareMode: "Compare Mode",
    compareModeTooltip: "Enable to select two flags for comparison",
    exitCompareMode: "Exit Compare Mode",
    selectForComparison: "Select {{countryName}} for comparison",
    compareFlags: "Compare ({{count}}/2)",
    clearSelection: "Clear",
    comparisonTitle: "Flag Comparison",
    favorites: "Favorites",
    noFavorites: "No favorites yet!",
    noFavoritesDescription: "Click the heart on any flag to add it to your collection.",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    addedToFavoritesToast: "{{countryName}} added to favorites!",
    removedFromFavoritesToast: "{{countryName}} removed from favorites.",
    toggleTheme: "Toggle theme",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    continentTab: "Continents",
    toolsTab: "Tools",
    quizStreak: "🔥 {{count}} Streak",
    quizHint: "Hint ({{count}} left)",
    quizNoHints: "No hints left",
    quizReviewAnswers: "Review Answers",
    quizBackToSummary: "Back to Summary",
    quizReviewTitle: "Quiz Review",
    quizYourAnswer: "Your answer:",
    quizCorrectAnswer: "Correct answer:",
    continentHint: "Hint: The country is in {{continent}}.",
    quizBestStreak: "Best Streak",
    quizAccuracy: "Accuracy",
    quizRank: "Your Rank",
    rankNovice: "Flag Novice",
    rankApprentice: "Flag Apprentice",
    rankAdept: "Vexillology Adept",
    rankExpert: "Flag Expert",
    rankMaster: "Geography Genius",
    quiz5050Hint: "50:50 ({{count}} left)",
    quizNo5050Hints: "No 50:50 left",
    quizCorrect: "Correct",
    quizIncorrect: "Incorrect",
    sortBy: "Sort by",
    sortNameAsc: "Name (A-Z)",
    sortNameDesc: "Name (Z-A)",
    sortPopAsc: "Population (Low-High)",
    sortPopDesc: "Population (High-Low)",
    sortAreaAsc: "Area (Low-High)",
    sortAreaDesc: "Area (High-Low)",
    selectACountry: "Select a Country",
    uniqueFlags: "Unique Flags",
    uniqueFlagOfTheDayTitle: "Unique Flag of the Day",
    flagFactsTitle: "Vexillology Facts",
    showAnotherFact: "Show another fact",
    achievementsSubtitle: "Track your achievements and milestones in exploring world flags.",
    symbolismExplorerTitle: "Symbolism Explorer",
    symbolSun: "Sun",
    symbolCrescent: "Crescent",
    symbolCross: "Cross",
    symbolStar: "Star",
    symbolAnimal: "Animal",
    symbolWeapon: "Weapon",
    symbolMap: "Map",
    symbolBuilding: "Building",
    noFlagsForSymbol: "No flags found for this symbol.",
    achievementUnlocked: "Achievement Unlocked!",
    progress: "Progress",
    newBadge: "NEW",
    cat_explorer: "World Explorer",
    cat_quiz: "Quiz Master",
    cat_collector: "Great Collector",
    cat_designer: "Creative Soul",
    achFirstStepsTitle: "First Steps",
    achFirstStepsDesc: "Explore your first flag.",
    achWorldTravelerTitle: "World Traveler",
    achWorldTravelerDesc: "Explore 50 different flags.",
    achVexExpertTitle: "Vexpert",
    achVexExpertDesc: "Explore 150 different flags.",
    achQuizStarterTitle: "Academic Start",
    achQuizStarterDesc: "Complete your first quiz.",
    achPerfectScoreTitle: "Perfect Accuracy",
    achPerfectScoreDesc: "Get 100% correct in a quiz.",
    achStreakMasterTitle: "Unstoppable",
    achStreakMasterDesc: "Get a 10-answer streak.",
    achCuratorTitle: "Flag Curator",
    achCuratorDesc: "Add 10 flags to your favorites.",
    achArtistTitle: "Future Designer",
    achArtistDesc: "Create and download your first flag design.",
    flagFactsList: "[\"**Nepal** is the only country in the world with a non-quadrilateral flag.\", \"The flag of **Denmark** is the oldest national flag in continuous use, dating back to 1219.\", \"**Jamaica** is the only current national flag that does not contain the colors red, white, or blue.\", \"**Switzerland** and the **Vatican City** are the only two sovereign states with square national flags.\", \"The flag of **Mozambique** is the only one to feature a modern assault rifle, symbolizing defense.\", \"**Belize** has the only national flag that features human beings as a major element.\", \"The flag of the **Philippines** is unique because it is flown upside down (red on top) in times of war.\", \"**Libya** once had the world's only national flag consisting of a single solid color: green.\", \"The sun and moon on the flag of **Nepal** symbolize the hope that the nation will last as long as these celestial bodies.\", \"The colors on South Africa's **Rainbow Nation** flag represent unity among its diverse people.\"]",
    mapTitle: "World Map",
    mapSubtitle: "Explore the globe and discover nations by their location.",
    mapComingSoon: "Interactive Explorer",
    mapModeInstructions: "Use the map to browse countries geographically. Click on a country tag to see its full flag and details.",
    nepalFlagDesc: "The only non-quadrilateral national flag in the world.",
    switzerlandFlagDesc: "One of only two square sovereign state flags.",
    vaticanFlagDesc: "The other of only two square sovereign state flags.",
    paraguayFlagDesc: "The only national flag with different motifs on its obverse and reverse.",
    denmarkFlagDesc: "The oldest national flag in continuous use.",
    philippinesFlagDesc: "Flown upside down during times of war.",
    mozambiqueFlagDesc: "The only flag featuring a modern assault rifle.",
    qatarFlagDesc: "The only national flag with a width more than twice its height.",
    belizeFlagDesc: "The only national flag featuring human beings as a major element.",
    cyprusFlagDesc: "Features the map of the island.",
    brazilFlagDesc: "Features a celestial globe with 27 stars.",
    austriaFlagDesc: "One of the oldest national flags in the world.",
    lesothoFlagDesc: "Features a mokorotlo, a traditional Basotho straw hat.",
    cambodiaFlagDesc: "The only flag to feature a building (Angkor Wat).",
    turkmenistanFlagDesc: "Known for having the most detailed flag design.",
    sriLankaFlagDesc: "Features a gold lion holding a kastane sword.",
    canadaFlagDesc: "The iconic maple leaf was adopted in 1965.",
    southAfricaFlagDesc: "The 'Rainbow Nation' flag adopted after apartheid.",
    dominicanRepublicFlagDesc: "The only flag to feature a Bible.",
    jamaicaFlagDesc: "One of the few flags without red, white, or blue.",
    norwayFlagDesc: "The 'Mother of all flags' contains several other flags within it.",
    ugandaFlagDesc: "Features a Grey Crowned Crane in the center.",
    bhutanFlagDesc: "Features the Druk, the Thunder Dragon of Bhutanese mythology.",
    libyaFlagDesc: "Previously the only solid green flag in the world.",
    saudiArabiaFlagDesc: "Features the Shahada and a sword; never flown at half-mast.",
    kiribatiFlagDesc: "Features a frigatebird flying over a rising sun and sea.",
    dominicaFlagDesc: "Features a Sisserou parrot, endemic to the island.",
    eswatiniFlagDesc: "Features a shield and two spears from the Emasotsha regiment.",
    southKoreaFlagDesc: "Features the Taegeuk symbol, representing the balance of the universe (yin and yang).",
    lebanonFlagDesc: "Features the green Lebanon Cedar, a symbol of holiness, eternity and peace.",
    kenyaFlagDesc: "Features a traditional Maasai shield and two spears, symbolizing defense of freedom.",
    grenadaFlagDesc: "Known as the Spice Island, its flag features a clove of nutmeg in the hoist.",
    mexicoFlagDesc: "Depicts an ancient Aztec legend of an eagle perched on a cactus devouring a snake.",
    kyrgyzstanFlagDesc: "The yellow sun features 40 rays for the 40 tribes, and a 'tunduk' (yurt roof) in the center.",
    antiguaBarbudaFlagDesc: "The black represents African heritage, the sun a new era, and the blue hope.",
    seychellesFlagDesc: "Features five radiating bands representing a dynamic new country moving into the future.",
    vanuatuFlagDesc: "Features a boar's tusk (symbol of prosperity) and crossed namele leaves (peace).",
    eritreaFlagDesc: "Features an olive branch wreath, symbolizing the country's autonomy.",
    filterByColor: "Filter by Color",
    showingFlagsWith: "Showing flags with {{color}}",
    noFlagsForColor: "No flags found for this color.",
    bicolorHorizontal: "Bicolor Horizontal",
    bicolorVertical: "Bicolor Vertical",
    tricolorHorizontal: "Tricolor Horizontal",
    tricolorVertical: "Tricolor Vertical",
    nordicCross: "Nordic Cross",
    noSymbol: "No Symbol",
    star: "Star",
    circle: "Circle",
    mainColor: "Color {{n}}",
    crossColor: "Cross Color",
    colorN: "Color {{n}}",
    flagDesignerTitle: "Flag Designer",
    flagDesignerSubtitle: "Create your own unique flag design using common vexillological patterns and symbols.",
    layout: "Layout",
    colors: "Colors",
    symbol: "Symbol",
    symbolColor: "Symbol Color",
    actions: "Actions",
    randomize: "Randomize",
    download: "Download",
    guessTheFlag: "Guess the Flag",
    guessesLeft: "{{count}} guesses left",
    congratulations: "Congratulations!",
    gameOver: "Game Over",
    correctAnswerWas: "The correct answer was {{country}}",
    nextFlagIn: "Next flag in",
    enterCountryName: "Enter country name...",
    all: "All",
    allQuestions: "All Questions",
    numberOfQuestions: "{{count}} Questions",
    selectNumberOfQuestions: "Select Number of Questions"
  },
  pt: {
    title: "Explorador de Bandeiras do Mundo",
    headerTitle: "Bandeiras do Mundo",
    explorer: "Explorador",
    exploreTitle: "Bandeira do Dia",
    exploreSubtitle: "Descubra as histórias, símbolos e cores por trás das bandeiras das nações. Use os filtros abaixo para navegar pela rica tapeçaria da heráldica global.",
    searchPlaceholder: "Pesquisar por nome do país...",
    fetchError: "Falha ao buscar dados dos países. Por favor, tente novamente mais tarde.",
    api_fetch_error: "Não foi possível carregar os dados das bandeiras. Verifique sua conexão.",
    errorOops: "Opa! Algo deu errado.",
    noResults: "Nenhuma bandeira corresponde aos seus critérios de pesquisa.",
    noFlagsFound: "Nenhuma Bandeira Encontrada",
    noFlagsFoundDescription: "Tente ajustar sua busca ou filtro para encontrar o que procura.",
    viewDetailsFor: "Ver detalhes de {{countryName}}",
    flagOf: "Bandeira de {{country}}",
    closeModal: "Fechar modal",
    continents: "Continente(s)",
    capital: "Capital",
    population: "População",
    area: "Área",
    areaUnit: "km²",
    coatOfArms: "Brasão de Armas",
    viewOnMap: "Ver no Google Maps",
    goToTop: "Ir para o topo",
    footerRights: `© ${new Date().getFullYear()} Explorador de Bandeiras do Mundo. Todos os direitos reservados.`,
    footerBuiltWith: "Construído com React & Tailwind CSS | Dados da API REST Countries",
    showingFlags: "Mostrando {{count}} de {{total}} bandeiras",
    loadingFlags: "Carregando bandeiras de todo o mundo...",
    startQuiz: "Iniciar Quiz",
    quizTitle: "Quiz",
    questionOf: "Questão {{current}} de {{total}}",
    whichCountry: "De que país é esta bandeira?",
    whichFlag: "Qual bandeira pertence a {{country}}?",
    nextQuestion: "Próxima Pergunta",
    quizResults: "Resultados do Quiz",
    yourScore: "Você acertou {{score}} de {{total}}",
    playAgain: "Jogar Novamente",
    backToExplorer: "Voltar ao Explorador",
    scoreFeedbackExcellent: "Excelente! Você é um expert em bandeiras!",
    scoreFeedbackGood: "Bom trabalho! Você conhece bem as bandeiras.",
    scoreFeedbackAverage: "Nada mal! Com um pouco mais de prática você será um expert.",
    scoreFeedbackPoor: "Continue praticando! O mundo das bandeiras é fascinante.",
    discoverTitle: "Descubra",
    discoverIntro: "Mergulhe fundo no mundo da vexilologia. Explore temas comuns, designs únicos e o rico simbolismo presente nas bandeiras do mundo.",
    discoverLoading: "Criando uma nova coleção para você...",
    flagOfTheDay: "Bandeira do Dia",
    flagOfTheDayLoading: "Selecionando a bandeira em destaque de hoje...",
    filterAndSearch: "Filtrar e Pesquisar",
    filterByContinent: "Filtrar por Continente",
    quizSetupTitle: "Configuração do Quiz",
    chooseMode: "Escolha um Modo de Jogo",
    selectDifficulty: "Selecione a Dificuldade",
    difficultyEasy: "Fácil",
    difficultyMedium: "Médio",
    difficultyHard: "Difícil",
    difficultyEasyDesc: "Países mais populosos.",
    difficultyMediumDesc: "Uma mistura de todos os países.",
    difficultyHardDesc: "Países menos conhecidos.",
    modeFlagToCountry: "Bandeira ➞ País",
    modeFlagToCountryDesc: "Adivinhe o país pela bandeira.",
    modeCountryToFlag: "País ➞ Bandeira",
    modeCountryToFlagDesc: "Encontre a bandeira correta para o país.",
    modeFlagToCapital: "Bandeira ➞ Capital",
    modeFlagToCapitalDesc: "Identifique a capital pela bandeira.",
    modeCountryToCapital: "País ➞ Capital",
    modeCountryToCapitalDesc: "Adivinhe a capital do país.",
    whichCapitalForCountry: "Qual é a capital de {{country}}?",
    modeShapeToCountry: "Brasão ➞ País",
    modeShapeToCountryDesc: "Reconheça o país pelo seu brasão de armas.",
    whichCapital: "A qual cidade capital esta bandeira pertence?",
    whichCoatOfArms: "De que país é este brasão de armas?",
    modeFlagle: "Flagle",
    modeFlagleDesc: "Adivinhe o país por uma bandeira pixelada.",
    modeOddOneOut: "Qual é o Intruso?",
    modeOddOneOutDesc: "Encontre a bandeira de uma região diferente.",
    whichIsTheOddOneOut: "Qual bandeira é a intrusa?",
    backToMenu: "Voltar ao Menu",
    quizTime: "Tempo Total",
    quizAvgTime: "Tempo Médio / Q",
    quizSeconds: "{{seconds}}s",
    compareMode: "Modo de Comparação",
    compareModeTooltip: "Ative para selecionar duas bandeiras para comparação",
    exitCompareMode: "Sair do Modo de Comparação",
    selectForComparison: "Selecionar {{countryName}} para comparação",
    compareFlags: "Comparar ({{count}}/2)",
    clearSelection: "Limpar",
    comparisonTitle: "Comparação de Bandeiras",
    favorites: "Favoritos",
    noFavorites: "Nenhum favorito ainda!",
    noFavoritesDescription: "Clique no coração em qualquer bandeira para adicioná-la à sua coleção.",
    addToFavorites: "Adicionar aos favoritos",
    removeFromFavorites: "Remover dos favoritos",
    addedToFavoritesToast: "{{countryName}} adicionado aos favoritos!",
    removedFromFavoritesToast: "{{countryName}} removido dos favoritos.",
    toggleTheme: "Alternar tema",
    scrollLeft: "Rolar para a esquerda",
    scrollRight: "Rolar para a direita",
    continentTab: "Continentes",
    toolsTab: "Ferramentas",
    quizStreak: "🔥 Sequência de {{count}}",
    quizHint: "Dica (restam {{count}})",
    quizNoHints: "Nenhuma dica restante",
    quizReviewAnswers: "Rever Respostas",
    quizBackToSummary: "Voltar ao Resumo",
    quizReviewTitle: "Revisão do Quiz",
    quizYourAnswer: "Sua resposta:",
    quizCorrectAnswer: "Resposta correta:",
    continentHint: "Dica: O país fica em {{continent}}.",
    quizBestStreak: "Melhor Sequência",
    quizAccuracy: "Precisão",
    quizRank: "Sua Classificação",
    rankNovice: "Iniciante em Bandeiras",
    rankApprentice: "Aprendiz de Bandeiras",
    rankAdept: "Adepto em Vexilologia",
    rankExpert: "Expert em Bandeiras",
    rankMaster: "Gênio da Geografia",
    quiz5050Hint: "50:50 (restam {{count}})",
    quizNo5050Hints: "Nenhuma 50:50 restante",
    quizCorrect: "Corretas",
    quizIncorrect: "Incorretas",
    sortBy: "Ordenar por",
    sortNameAsc: "Nome (A-Z)",
    sortNameDesc: "Nome (Z-A)",
    sortPopAsc: "População (Baixa-Alta)",
    sortPopDesc: "População (Alta-Baixa)",
    sortAreaAsc: "Área (Baixa-Alta)",
    sortAreaDesc: "Área (Alta-Baixa)",
    selectACountry: "Selecione um País",
    uniqueFlags: "Bandeiras Únicas",
    uniqueFlagOfTheDayTitle: "Bandeira Única do Dia",
    flagFactsTitle: "Curiosidades Vexilológicas",
    showAnotherFact: "Mostrar outra curiosidade",
    achievementsSubtitle: "Acompanhe suas conquistas e marcos na exploração das bandeiras do mundo.",
    symbolismExplorerTitle: "Explorador de Símbolos",
    symbolSun: "Sol",
    symbolCrescent: "Crescente",
    symbolCross: "Cruz",
    symbolStar: "Estrela",
    symbolAnimal: "Animal",
    symbolMap: "Mapa",
    symbolBuilding: "Edifício",
    symbolWeapon: "Arma",
    noFlagsForSymbol: "Nenhuma bandeira encontrada para este símbolo.",
    achievementUnlocked: "Conquista Desbloqueada!",
    progress: "Progresso",
    newBadge: "NOVO",
    cat_explorer: "Explorador do Mundo",
    cat_quiz: "Mestre do Quiz",
    cat_collector: "Grande Colecionador",
    cat_designer: "Alma Criativa",
    achFirstStepsTitle: "Primeiros Passos",
    achFirstStepsDesc: "Explore sua primeira bandeira.",
    achWorldTravelerTitle: "Viajante do Mundo",
    achWorldTravelerDesc: "Explore 50 bandeiras diferentes.",
    achVexExpertTitle: "Vexilologista Expert",
    achVexExpertDesc: "Explore 150 bandeiras diferentes.",
    achQuizStarterTitle: "Início Acadêmico",
    achQuizStarterDesc: "Complete seu primeiro quiz.",
    achPerfectScoreTitle: "Precisão Perfeita",
    achPerfectScoreDesc: "Acerte 100% das questões em um quiz.",
    achStreakMasterTitle: "Imparável",
    achStreakMasterDesc: "Consiga uma sequência de 10 acertos.",
    achCuratorTitle: "Curador de Bandeiras",
    achCuratorDesc: "Adicione 10 bandeiras aos seus favoritos.",
    achArtistTitle: "Futuro Designer",
    achArtistDesc: "Crie e baixe seu primeiro design de bandeira.",
    flagFactsList: "[\"O **Nepal** é o único país do mundo com uma bandeira não quadrilátera.\", \"A bandeira da **Dinamarca** é a bandeira nacional mais antiga em uso contínuo, datando de 1219.\", \"A **Jamaica** é a única bandeira nacional atual que não contém as cores vermelho, branco ou azul.\", \"A **Suíça** e o **Vaticano** são os únicos dois estados soberanos com bandeiras nacionais quadradas.\", \"A bandeira de **Moçambique** é a única a apresentar um rifle de assalto moderno, simbolizando a defesa.\", \"**Belize** tem a única bandeira nacional que apresenta seres humanos como elemento principal.\", \"A bandeira das **Filipinas** é única porque é hasteada de cabeça para baixo (vermelho no topo) em tempos de guerra.\", \"A **Líbia** já teve a única bandeira nacional do mundo consistindo de uma única cor sólida: verde.\", \"O sol e a lua na bandeira do **Nepal** simbolizam a esperança de que a nação dure tanto quanto esses corpos celestes.\", \"As cores na bandeira da **Nação Arco-Íris** da África do Sul representam a unidade entre seu povo diversificado.\"]",
    mapTitle: "Mapa Mundi",
    mapSubtitle: "Explore o globo e descubra nações por sua localização.",
    mapComingSoon: "Explorador Geográfico",
    mapModeInstructions: "Utilize o mapa para navegar pelos países. Clique em uma tag de país para abrir sua bandeira e detalhes.",
    nepalFlagDesc: "A única bandeira nacional não quadrilátera do mundo.",
    switzerlandFlagDesc: "Uma das duas únicas bandeiras quadradas de estados soberanos.",
    vaticanFlagDesc: "A outra das duas únicas bandeiras quadradas de estados soberanos.",
    paraguayFlagDesc: "A única bandeira nacional com brasões diferentes no anverso e no reverso.",
    denmarkFlagDesc: "A bandeira nacional mais antiga em uso contínuo.",
    philippinesFlagDesc: "Hasteada de cabeça para baixo em tempos de guerra.",
    mozambiqueFlagDesc: "A única bandeira que apresenta um rifle de assalto moderno.",
    qatarFlagDesc: "A única bandeira nacional com largura mais de duas vezes sua altura.",
    belizeFlagDesc: "A única bandeira nacional que apresenta seres humanos como elemento principal.",
    cyprusFlagDesc: "Apresenta o mapa da ilha.",
    brazilFlagDesc: "Apresenta um globo azul com 27 estrelas e a faixa 'Ordem e Progresso'.",
    austriaFlagDesc: "Uma das bandeiras nacionais mais antigas do mundo.",
    lesothoFlagDesc: "Apresenta um mokorotlo, um chapéu de palha tradicional do Basoto.",
    cambodiaFlagDesc: "A única bandeira a apresentar um edifício (Angkor Wat).",
    turkmenistanFlagDesc: "Conhecida por ter o design de bandeira mais detalhado.",
    sriLankaFlagDesc: "Apresenta um leão dourado segurando uma espada kastane.",
    canadaFlagDesc: "A icônica folha de bordo foi adotada em 1965.",
    southAfricaFlagDesc: "A bandeira da 'Nação Arco-Íris' adotada após o apartheid.",
    dominicanRepublicFlagDesc: "A única bandeira que apresenta uma Bíblia.",
    jamaicaFlagDesc: "Uma das poucas bandeiras sem vermelho, branco ou azul.",
    norwayFlagDesc: "A 'Mãe de todas as bandeiras' contém várias outras bandeiras dentro dela.",
    ugandaFlagDesc: "Apresenta um Grou-coroado no centro.",
    bhutanFlagDesc: "Apresenta o Druk, o Dragão do Trovão da mitologia butanesa.",
    libyaFlagDesc: "Anteriormente a única bandeira verde sólida do mundo.",
    saudiArabiaFlagDesc: "Apresenta a Shahada e uma espada; nunca hasteada a meio-mastro.",
    kiribatiFlagDesc: "Apresenta uma fragata voando sobre o sol nascente e o mar.",
    dominicaFlagDesc: "Apresenta um papagaio-imperial, endêmico da ilha.",
    eswatiniFlagDesc: "Apresenta um escudo e duas lanças do regimento Emasotsha.",
    southKoreaFlagDesc: "Apresenta o símbolo Taegeuk, representando o equilíbrio do universe (yin e yang).",
    lebanonFlagDesc: "Apresenta o Cedro-do-Líbano verde, um símbolo de santidade, eternidade e paz.",
    kenyaFlagDesc: "Apresenta um escudo tradicional Maasai e duas lanças, simbolizando a defesa da liberdade.",
    grenadaFlagDesc: "Conhecida como a Ilha das Especiarias, sua bandeira apresenta um dente de noz-moscada.",
    mexicoFlagDesc: "Retrata uma antiga lenda asteca de uma águia pousada em um cacto devorando uma serpente.",
    kyrgyzstanFlagDesc: "O sol amarelo possui 40 raios para as 40 tribos e um 'tunduk' (teto de iurta) no centro.",
    antiguaBarbudaFlagDesc: "O preto representa a herança africana, o sol uma nova era e o azul a esperança.",
    seychellesFlagDesc: "Apresenta cinco faixas radiantes representando um novo país dinâmico em direção ao futuro.",
    vanuatuFlagDesc: "Apresenta uma presa de javali (símbolo de prosperidade) e folhas de namele cruzadas (paz).",
    eritreaFlagDesc: "Apresenta uma coroa de ramos de oliveira, simbolizando a autonomia do país.",
    filterByColor: "Filtrar por Cor",
    showingFlagsWith: "Mostrando bandeiras com {{color}}",
    noFlagsForColor: "Nenhuma bandeira encontrada para esta cor.",
    bicolorHorizontal: "Bicolor Horizontal",
    bicolorVertical: "Bicolor Vertical",
    tricolorHorizontal: "Tricolor Horizontal",
    tricolorVertical: "Tricolor Vertical",
    nordicCross: "Cruz Nórdica",
    noSymbol: "Sem Símbolo",
    star: "Estrela",
    circle: "Círculo",
    mainColor: "Cor Principal",
    crossColor: "Cor da Cruz",
    colorN: "Cor {{n}}",
    flagDesignerTitle: "Designer de Bandeiras",
    flagDesignerSubtitle: "Crie seu próprio design de bandeira único usando padrões e símbolos vexilológicos comuns.",
    layout: "Layout",
    colors: "Cores",
    symbol: "Símbolo",
    symbolColor: "Cor do Símbolo",
    actions: "Ações",
    randomize: "Aleatório",
    download: "Baixar",
    guessTheFlag: "Adivinhe a Bandeira",
    guessesLeft: "{{count}} tentativas restantes",
    congratulations: "Parabéns!",
    gameOver: "Fim de Jogo",
    correctAnswerWas: "A resposta correta era {{country}}",
    nextFlagIn: "Próxima bandeira em",
    enterCountryName: "Digite o nome do país...",
    all: "Todas",
    allQuestions: "Todas as Questões",
    numberOfQuestions: "{{count}} Questões",
    selectNumberOfQuestions: "Selecione o Número de Questões"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        if (saved === 'en' || saved === 'pt') return saved;
        return navigator.language.startsWith('pt') ? 'pt' : 'en';
    });

    const setLanguage = useCallback((lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
        document.documentElement.lang = lang;
    }, []);

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const t = useCallback((key: string, replacements?: { [key: string]: string }) => {
        let text = translations[language][key] || translations['en'][key] || key;
        
        if (replacements) {
            Object.entries(replacements).forEach(([k, v]) => {
                text = text.replace(`{{${k}}}`, v);
            });
        }
        
        return text;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
